// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.5.1
// source: gm/gm.proto

package gm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//查询账号对应的uid
type GetUidByAcc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUidByAcc) Reset() {
	*x = GetUidByAcc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gm_gm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUidByAcc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUidByAcc) ProtoMessage() {}

func (x *GetUidByAcc) ProtoReflect() protoreflect.Message {
	mi := &file_gm_gm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUidByAcc.ProtoReflect.Descriptor instead.
func (*GetUidByAcc) Descriptor() ([]byte, []int) {
	return file_gm_gm_proto_rawDescGZIP(), []int{0}
}

type GetUidByAcc_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *GetUidByAcc_Request) Reset() {
	*x = GetUidByAcc_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gm_gm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUidByAcc_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUidByAcc_Request) ProtoMessage() {}

func (x *GetUidByAcc_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gm_gm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUidByAcc_Request.ProtoReflect.Descriptor instead.
func (*GetUidByAcc_Request) Descriptor() ([]byte, []int) {
	return file_gm_gm_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetUidByAcc_Request) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type GetUidByAcc_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetUidByAcc_Reply) Reset() {
	*x = GetUidByAcc_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gm_gm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUidByAcc_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUidByAcc_Reply) ProtoMessage() {}

func (x *GetUidByAcc_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_gm_gm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUidByAcc_Reply.ProtoReflect.Descriptor instead.
func (*GetUidByAcc_Reply) Descriptor() ([]byte, []int) {
	return file_gm_gm_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetUidByAcc_Reply) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_gm_gm_proto protoreflect.FileDescriptor

var file_gm_gm_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x6d, 0x2f, 0x67, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x67,
	0x6d, 0x22, 0x4d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x69, 0x64, 0x42, 0x79, 0x41, 0x63, 0x63,
	0x1a, 0x23, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x19, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x42, 0x10, 0x5a, 0x0e, 0x6c, 0x61, 0x69, 0x79, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gm_gm_proto_rawDescOnce sync.Once
	file_gm_gm_proto_rawDescData = file_gm_gm_proto_rawDesc
)

func file_gm_gm_proto_rawDescGZIP() []byte {
	file_gm_gm_proto_rawDescOnce.Do(func() {
		file_gm_gm_proto_rawDescData = protoimpl.X.CompressGZIP(file_gm_gm_proto_rawDescData)
	})
	return file_gm_gm_proto_rawDescData
}

var file_gm_gm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gm_gm_proto_goTypes = []interface{}{
	(*GetUidByAcc)(nil),         // 0: gm.GetUidByAcc
	(*GetUidByAcc_Request)(nil), // 1: gm.GetUidByAcc.Request
	(*GetUidByAcc_Reply)(nil),   // 2: gm.GetUidByAcc.Reply
}
var file_gm_gm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gm_gm_proto_init() }
func file_gm_gm_proto_init() {
	if File_gm_gm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gm_gm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUidByAcc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gm_gm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUidByAcc_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gm_gm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUidByAcc_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gm_gm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gm_gm_proto_goTypes,
		DependencyIndexes: file_gm_gm_proto_depIdxs,
		MessageInfos:      file_gm_gm_proto_msgTypes,
	}.Build()
	File_gm_gm_proto = out.File
	file_gm_gm_proto_rawDesc = nil
	file_gm_gm_proto_goTypes = nil
	file_gm_gm_proto_depIdxs = nil
}
