// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.5.1
// source: outer/group_plugin_activity.proto

package outer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "laiya/proto/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//群活动摘要信息
type GroupActivitySummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId    uint64 `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"`      //活动id
	ActivityTitle string `protobuf:"bytes,2,opt,name=activityTitle,proto3" json:"activityTitle,omitempty"` //活动标题
	ActivityDes   string `protobuf:"bytes,3,opt,name=activityDes,proto3" json:"activityDes,omitempty"`     //活动描述
	BeginTime     int64  `protobuf:"varint,4,opt,name=beginTime,proto3" json:"beginTime,omitempty"`        //开始的时间戳
	EndTime       int64  `protobuf:"varint,5,opt,name=endTime,proto3" json:"endTime,omitempty"`            //结束的时间戳
	OwnerUid      uint64 `protobuf:"varint,6,opt,name=ownerUid,proto3" json:"ownerUid,omitempty"`          //创建者
}

func (x *GroupActivitySummary) Reset() {
	*x = GroupActivitySummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupActivitySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupActivitySummary) ProtoMessage() {}

func (x *GroupActivitySummary) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupActivitySummary.ProtoReflect.Descriptor instead.
func (*GroupActivitySummary) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{0}
}

func (x *GroupActivitySummary) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *GroupActivitySummary) GetActivityTitle() string {
	if x != nil {
		return x.ActivityTitle
	}
	return ""
}

func (x *GroupActivitySummary) GetActivityDes() string {
	if x != nil {
		return x.ActivityDes
	}
	return ""
}

func (x *GroupActivitySummary) GetBeginTime() int64 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *GroupActivitySummary) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GroupActivitySummary) GetOwnerUid() uint64 {
	if x != nil {
		return x.OwnerUid
	}
	return 0
}

//获取活动列表
type GetGroupAllActivity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,100100,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *GetGroupAllActivity) Reset() {
	*x = GetGroupAllActivity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupAllActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupAllActivity) ProtoMessage() {}

func (x *GetGroupAllActivity) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupAllActivity.ProtoReflect.Descriptor instead.
func (*GetGroupAllActivity) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{1}
}

func (x *GetGroupAllActivity) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//获取活动详情
type GetGroupActivityDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,100101,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *GetGroupActivityDetail) Reset() {
	*x = GetGroupActivityDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupActivityDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupActivityDetail) ProtoMessage() {}

func (x *GetGroupActivityDetail) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupActivityDetail.ProtoReflect.Descriptor instead.
func (*GetGroupActivityDetail) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupActivityDetail) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//创建活动
type CreateGroupActivity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,100102,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *CreateGroupActivity) Reset() {
	*x = CreateGroupActivity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupActivity) ProtoMessage() {}

func (x *CreateGroupActivity) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupActivity.ProtoReflect.Descriptor instead.
func (*CreateGroupActivity) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGroupActivity) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//修改活动信息
type UpdateGroupActivity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,100103,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *UpdateGroupActivity) Reset() {
	*x = UpdateGroupActivity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGroupActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupActivity) ProtoMessage() {}

func (x *UpdateGroupActivity) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupActivity.ProtoReflect.Descriptor instead.
func (*UpdateGroupActivity) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGroupActivity) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//删除活动
type DeleteGroupActivity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,100104,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *DeleteGroupActivity) Reset() {
	*x = DeleteGroupActivity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGroupActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupActivity) ProtoMessage() {}

func (x *DeleteGroupActivity) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupActivity.ProtoReflect.Descriptor instead.
func (*DeleteGroupActivity) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteGroupActivity) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//玩家报名参与活动~参加和修改都用这个
type SignUpGroupActivity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,100105,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *SignUpGroupActivity) Reset() {
	*x = SignUpGroupActivity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpGroupActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpGroupActivity) ProtoMessage() {}

func (x *SignUpGroupActivity) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpGroupActivity.ProtoReflect.Descriptor instead.
func (*SignUpGroupActivity) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{6}
}

func (x *SignUpGroupActivity) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//玩家取消报名
type SignOutGroupActivity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,100106,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *SignOutGroupActivity) Reset() {
	*x = SignOutGroupActivity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignOutGroupActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutGroupActivity) ProtoMessage() {}

func (x *SignOutGroupActivity) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutGroupActivity.ProtoReflect.Descriptor instead.
func (*SignOutGroupActivity) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{7}
}

func (x *SignOutGroupActivity) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//广播活动信息到群聊天群
type BroadcastGroupActivityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,100107,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *BroadcastGroupActivityInfo) Reset() {
	*x = BroadcastGroupActivityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastGroupActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastGroupActivityInfo) ProtoMessage() {}

func (x *BroadcastGroupActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastGroupActivityInfo.ProtoReflect.Descriptor instead.
func (*BroadcastGroupActivityInfo) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{8}
}

func (x *BroadcastGroupActivityInfo) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//广播上麦信息到群聊天群和个推
type BroadcastGroupActivityOnMic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,100108,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *BroadcastGroupActivityOnMic) Reset() {
	*x = BroadcastGroupActivityOnMic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastGroupActivityOnMic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastGroupActivityOnMic) ProtoMessage() {}

func (x *BroadcastGroupActivityOnMic) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastGroupActivityOnMic.ProtoReflect.Descriptor instead.
func (*BroadcastGroupActivityOnMic) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{9}
}

func (x *BroadcastGroupActivityOnMic) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

type GetGroupAllActivity_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`           //发送者的id--客户端不用设置
	Gid      uint64 `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`           //群id
	OnlySelf bool   `protobuf:"varint,3,opt,name=onlySelf,proto3" json:"onlySelf,omitempty"` //是否仅仅获取自己参与的
}

func (x *GetGroupAllActivity_Request) Reset() {
	*x = GetGroupAllActivity_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupAllActivity_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupAllActivity_Request) ProtoMessage() {}

func (x *GetGroupAllActivity_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupAllActivity_Request.ProtoReflect.Descriptor instead.
func (*GetGroupAllActivity_Request) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetGroupAllActivity_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetGroupAllActivity_Request) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *GetGroupAllActivity_Request) GetOnlySelf() bool {
	if x != nil {
		return x.OnlySelf
	}
	return false
}

type GetGroupAllActivity_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Activities []*GroupActivitySummary `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
}

func (x *GetGroupAllActivity_Reply) Reset() {
	*x = GetGroupAllActivity_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupAllActivity_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupAllActivity_Reply) ProtoMessage() {}

func (x *GetGroupAllActivity_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupAllActivity_Reply.ProtoReflect.Descriptor instead.
func (*GetGroupAllActivity_Reply) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetGroupAllActivity_Reply) GetActivities() []*GroupActivitySummary {
	if x != nil {
		return x.Activities
	}
	return nil
}

type GetGroupActivityDetail_GroupActivityDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId    uint64                                               `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"`      //活动id
	ActivityTitle string                                               `protobuf:"bytes,2,opt,name=activityTitle,proto3" json:"activityTitle,omitempty"` //活动标题
	ActivityDes   string                                               `protobuf:"bytes,3,opt,name=activityDes,proto3" json:"activityDes,omitempty"`     //活动描述
	BeginTime     int64                                                `protobuf:"varint,4,opt,name=beginTime,proto3" json:"beginTime,omitempty"`        //开始的时间戳
	EndTime       int64                                                `protobuf:"varint,5,opt,name=endTime,proto3" json:"endTime,omitempty"`            //结束的时间戳
	OwnerUid      uint64                                               `protobuf:"varint,6,opt,name=ownerUid,proto3" json:"ownerUid,omitempty"`          //创建者
	Players       []*GetGroupActivityDetail_GroupActivityDetail_Player `protobuf:"bytes,7,rep,name=players,proto3" json:"players,omitempty"`             //报名信息
}

func (x *GetGroupActivityDetail_GroupActivityDetail) Reset() {
	*x = GetGroupActivityDetail_GroupActivityDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupActivityDetail_GroupActivityDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupActivityDetail_GroupActivityDetail) ProtoMessage() {}

func (x *GetGroupActivityDetail_GroupActivityDetail) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupActivityDetail_GroupActivityDetail.ProtoReflect.Descriptor instead.
func (*GetGroupActivityDetail_GroupActivityDetail) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetGroupActivityDetail_GroupActivityDetail) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *GetGroupActivityDetail_GroupActivityDetail) GetActivityTitle() string {
	if x != nil {
		return x.ActivityTitle
	}
	return ""
}

func (x *GetGroupActivityDetail_GroupActivityDetail) GetActivityDes() string {
	if x != nil {
		return x.ActivityDes
	}
	return ""
}

func (x *GetGroupActivityDetail_GroupActivityDetail) GetBeginTime() int64 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *GetGroupActivityDetail_GroupActivityDetail) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetGroupActivityDetail_GroupActivityDetail) GetOwnerUid() uint64 {
	if x != nil {
		return x.OwnerUid
	}
	return 0
}

func (x *GetGroupActivityDetail_GroupActivityDetail) GetPlayers() []*GetGroupActivityDetail_GroupActivityDetail_Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type GetGroupActivityDetail_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid        uint64 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`               //群id
	ActivityId uint64 `protobuf:"varint,2,opt,name=activityId,proto3" json:"activityId,omitempty"` //活动id
}

func (x *GetGroupActivityDetail_Request) Reset() {
	*x = GetGroupActivityDetail_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupActivityDetail_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupActivityDetail_Request) ProtoMessage() {}

func (x *GetGroupActivityDetail_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupActivityDetail_Request.ProtoReflect.Descriptor instead.
func (*GetGroupActivityDetail_Request) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GetGroupActivityDetail_Request) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *GetGroupActivityDetail_Request) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type GetGroupActivityDetail_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Activity *GetGroupActivityDetail_GroupActivityDetail `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
}

func (x *GetGroupActivityDetail_Reply) Reset() {
	*x = GetGroupActivityDetail_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupActivityDetail_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupActivityDetail_Reply) ProtoMessage() {}

func (x *GetGroupActivityDetail_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupActivityDetail_Reply.ProtoReflect.Descriptor instead.
func (*GetGroupActivityDetail_Reply) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{2, 2}
}

func (x *GetGroupActivityDetail_Reply) GetActivity() *GetGroupActivityDetail_GroupActivityDetail {
	if x != nil {
		return x.Activity
	}
	return nil
}

type GetGroupActivityDetail_GroupActivityDetail_Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`      //报名的uid
	Remark string `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"` //备注信息
}

func (x *GetGroupActivityDetail_GroupActivityDetail_Player) Reset() {
	*x = GetGroupActivityDetail_GroupActivityDetail_Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupActivityDetail_GroupActivityDetail_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupActivityDetail_GroupActivityDetail_Player) ProtoMessage() {}

func (x *GetGroupActivityDetail_GroupActivityDetail_Player) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupActivityDetail_GroupActivityDetail_Player.ProtoReflect.Descriptor instead.
func (*GetGroupActivityDetail_GroupActivityDetail_Player) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *GetGroupActivityDetail_GroupActivityDetail_Player) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetGroupActivityDetail_GroupActivityDetail_Player) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreateGroupActivity_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid           uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                    //发送者的id--客户端不用设置
	Gid           uint64 `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`                    //群id
	ActivityTitle string `protobuf:"bytes,3,opt,name=activityTitle,proto3" json:"activityTitle,omitempty"` //活动标题
	ActivityDes   string `protobuf:"bytes,4,opt,name=activityDes,proto3" json:"activityDes,omitempty"`     //活动描述
	BeginTime     int64  `protobuf:"varint,5,opt,name=beginTime,proto3" json:"beginTime,omitempty"`        //开始的时间戳
	EndTime       int64  `protobuf:"varint,6,opt,name=endTime,proto3" json:"endTime,omitempty"`            //结束的时间戳
}

func (x *CreateGroupActivity_Request) Reset() {
	*x = CreateGroupActivity_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupActivity_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupActivity_Request) ProtoMessage() {}

func (x *CreateGroupActivity_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupActivity_Request.ProtoReflect.Descriptor instead.
func (*CreateGroupActivity_Request) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CreateGroupActivity_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateGroupActivity_Request) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *CreateGroupActivity_Request) GetActivityTitle() string {
	if x != nil {
		return x.ActivityTitle
	}
	return ""
}

func (x *CreateGroupActivity_Request) GetActivityDes() string {
	if x != nil {
		return x.ActivityDes
	}
	return ""
}

func (x *CreateGroupActivity_Request) GetBeginTime() int64 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *CreateGroupActivity_Request) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type CreateGroupActivity_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Activity *GroupActivitySummary `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
}

func (x *CreateGroupActivity_Reply) Reset() {
	*x = CreateGroupActivity_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupActivity_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupActivity_Reply) ProtoMessage() {}

func (x *CreateGroupActivity_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupActivity_Reply.ProtoReflect.Descriptor instead.
func (*CreateGroupActivity_Reply) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{3, 1}
}

func (x *CreateGroupActivity_Reply) GetActivity() *GroupActivitySummary {
	if x != nil {
		return x.Activity
	}
	return nil
}

type UpdateGroupActivity_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid           uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                    //发送者的id--客户端不用设置
	Gid           uint64 `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`                    //群id
	ActivityId    uint64 `protobuf:"varint,3,opt,name=activityId,proto3" json:"activityId,omitempty"`      //活动id
	ActivityTitle string `protobuf:"bytes,4,opt,name=activityTitle,proto3" json:"activityTitle,omitempty"` //活动标题
	ActivityDes   string `protobuf:"bytes,5,opt,name=activityDes,proto3" json:"activityDes,omitempty"`     //活动描述
	BeginTime     int64  `protobuf:"varint,6,opt,name=beginTime,proto3" json:"beginTime,omitempty"`        //开始的时间戳
	EndTime       int64  `protobuf:"varint,7,opt,name=endTime,proto3" json:"endTime,omitempty"`            //结束的时间戳
}

func (x *UpdateGroupActivity_Request) Reset() {
	*x = UpdateGroupActivity_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGroupActivity_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupActivity_Request) ProtoMessage() {}

func (x *UpdateGroupActivity_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupActivity_Request.ProtoReflect.Descriptor instead.
func (*UpdateGroupActivity_Request) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UpdateGroupActivity_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateGroupActivity_Request) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *UpdateGroupActivity_Request) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *UpdateGroupActivity_Request) GetActivityTitle() string {
	if x != nil {
		return x.ActivityTitle
	}
	return ""
}

func (x *UpdateGroupActivity_Request) GetActivityDes() string {
	if x != nil {
		return x.ActivityDes
	}
	return ""
}

func (x *UpdateGroupActivity_Request) GetBeginTime() int64 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *UpdateGroupActivity_Request) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type UpdateGroupActivity_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Activity *GroupActivitySummary `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
}

func (x *UpdateGroupActivity_Reply) Reset() {
	*x = UpdateGroupActivity_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGroupActivity_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupActivity_Reply) ProtoMessage() {}

func (x *UpdateGroupActivity_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupActivity_Reply.ProtoReflect.Descriptor instead.
func (*UpdateGroupActivity_Reply) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{4, 1}
}

func (x *UpdateGroupActivity_Reply) GetActivity() *GroupActivitySummary {
	if x != nil {
		return x.Activity
	}
	return nil
}

type DeleteGroupActivity_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`               //发送者的id--客户端不用设置
	Gid        uint64 `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`               //群id
	ActivityId uint64 `protobuf:"varint,3,opt,name=activityId,proto3" json:"activityId,omitempty"` //活动id
}

func (x *DeleteGroupActivity_Request) Reset() {
	*x = DeleteGroupActivity_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGroupActivity_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupActivity_Request) ProtoMessage() {}

func (x *DeleteGroupActivity_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupActivity_Request.ProtoReflect.Descriptor instead.
func (*DeleteGroupActivity_Request) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{5, 0}
}

func (x *DeleteGroupActivity_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DeleteGroupActivity_Request) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *DeleteGroupActivity_Request) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type DeleteGroupActivity_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteGroupActivity_Reply) Reset() {
	*x = DeleteGroupActivity_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGroupActivity_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupActivity_Reply) ProtoMessage() {}

func (x *DeleteGroupActivity_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupActivity_Reply.ProtoReflect.Descriptor instead.
func (*DeleteGroupActivity_Reply) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{5, 1}
}

type SignUpGroupActivity_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`               //发送者的id--客户端不用设置
	Gid        uint64 `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`               //群id
	ActivityId uint64 `protobuf:"varint,3,opt,name=activityId,proto3" json:"activityId,omitempty"` //活动id
	Remark     string `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`          //备注
}

func (x *SignUpGroupActivity_Request) Reset() {
	*x = SignUpGroupActivity_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpGroupActivity_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpGroupActivity_Request) ProtoMessage() {}

func (x *SignUpGroupActivity_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpGroupActivity_Request.ProtoReflect.Descriptor instead.
func (*SignUpGroupActivity_Request) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{6, 0}
}

func (x *SignUpGroupActivity_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SignUpGroupActivity_Request) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *SignUpGroupActivity_Request) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *SignUpGroupActivity_Request) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type SignUpGroupActivity_Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`      //报名的uid
	Remark string `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"` //备注信息
}

func (x *SignUpGroupActivity_Player) Reset() {
	*x = SignUpGroupActivity_Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpGroupActivity_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpGroupActivity_Player) ProtoMessage() {}

func (x *SignUpGroupActivity_Player) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpGroupActivity_Player.ProtoReflect.Descriptor instead.
func (*SignUpGroupActivity_Player) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{6, 1}
}

func (x *SignUpGroupActivity_Player) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SignUpGroupActivity_Player) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type SignUpGroupActivity_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *SignUpGroupActivity_Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *SignUpGroupActivity_Reply) Reset() {
	*x = SignUpGroupActivity_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpGroupActivity_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpGroupActivity_Reply) ProtoMessage() {}

func (x *SignUpGroupActivity_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpGroupActivity_Reply.ProtoReflect.Descriptor instead.
func (*SignUpGroupActivity_Reply) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{6, 2}
}

func (x *SignUpGroupActivity_Reply) GetPlayer() *SignUpGroupActivity_Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type SignOutGroupActivity_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`               //发送者的id--客户端不用设置
	Gid        uint64 `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`               //群id
	ActivityId uint64 `protobuf:"varint,3,opt,name=activityId,proto3" json:"activityId,omitempty"` //活动id
}

func (x *SignOutGroupActivity_Request) Reset() {
	*x = SignOutGroupActivity_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignOutGroupActivity_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutGroupActivity_Request) ProtoMessage() {}

func (x *SignOutGroupActivity_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutGroupActivity_Request.ProtoReflect.Descriptor instead.
func (*SignOutGroupActivity_Request) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{7, 0}
}

func (x *SignOutGroupActivity_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SignOutGroupActivity_Request) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *SignOutGroupActivity_Request) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type SignOutGroupActivity_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SignOutGroupActivity_Reply) Reset() {
	*x = SignOutGroupActivity_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignOutGroupActivity_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutGroupActivity_Reply) ProtoMessage() {}

func (x *SignOutGroupActivity_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutGroupActivity_Reply.ProtoReflect.Descriptor instead.
func (*SignOutGroupActivity_Reply) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{7, 1}
}

type BroadcastGroupActivityInfo_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`               //发送者的id--客户端不用设置
	Gid        uint64 `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`               //群id
	ActivityId uint64 `protobuf:"varint,3,opt,name=activityId,proto3" json:"activityId,omitempty"` //活动id
}

func (x *BroadcastGroupActivityInfo_Request) Reset() {
	*x = BroadcastGroupActivityInfo_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastGroupActivityInfo_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastGroupActivityInfo_Request) ProtoMessage() {}

func (x *BroadcastGroupActivityInfo_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastGroupActivityInfo_Request.ProtoReflect.Descriptor instead.
func (*BroadcastGroupActivityInfo_Request) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{8, 0}
}

func (x *BroadcastGroupActivityInfo_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BroadcastGroupActivityInfo_Request) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *BroadcastGroupActivityInfo_Request) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type BroadcastGroupActivityInfo_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BroadcastGroupActivityInfo_Reply) Reset() {
	*x = BroadcastGroupActivityInfo_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastGroupActivityInfo_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastGroupActivityInfo_Reply) ProtoMessage() {}

func (x *BroadcastGroupActivityInfo_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastGroupActivityInfo_Reply.ProtoReflect.Descriptor instead.
func (*BroadcastGroupActivityInfo_Reply) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{8, 1}
}

type BroadcastGroupActivityOnMic_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`               //发送者的id--客户端不用设置
	Gid        uint64 `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`               //群id
	ActivityId uint64 `protobuf:"varint,3,opt,name=activityId,proto3" json:"activityId,omitempty"` //活动id
}

func (x *BroadcastGroupActivityOnMic_Request) Reset() {
	*x = BroadcastGroupActivityOnMic_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastGroupActivityOnMic_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastGroupActivityOnMic_Request) ProtoMessage() {}

func (x *BroadcastGroupActivityOnMic_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastGroupActivityOnMic_Request.ProtoReflect.Descriptor instead.
func (*BroadcastGroupActivityOnMic_Request) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{9, 0}
}

func (x *BroadcastGroupActivityOnMic_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BroadcastGroupActivityOnMic_Request) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *BroadcastGroupActivityOnMic_Request) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type BroadcastGroupActivityOnMic_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BroadcastGroupActivityOnMic_Reply) Reset() {
	*x = BroadcastGroupActivityOnMic_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_group_plugin_activity_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastGroupActivityOnMic_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastGroupActivityOnMic_Reply) ProtoMessage() {}

func (x *BroadcastGroupActivityOnMic_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_group_plugin_activity_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastGroupActivityOnMic_Reply.ProtoReflect.Descriptor instead.
func (*BroadcastGroupActivityOnMic_Reply) Descriptor() ([]byte, []int) {
	return file_outer_group_plugin_activity_proto_rawDescGZIP(), []int{9, 1}
}

var File_outer_group_plugin_activity_proto protoreflect.FileDescriptor

var file_outer_group_plugin_activity_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x1a, 0x18, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x2f, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd2, 0x01, 0x0a, 0x14, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x44, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x65,
	0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62,
	0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x69, 0x64, 0x22, 0xbe,
	0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x6c, 0x6c, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x18,
	0x84, 0x8e, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x1a, 0x49,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x67,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x6f, 0x6e, 0x6c, 0x79, 0x53, 0x65, 0x6c, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x6f, 0x6e, 0x6c, 0x79, 0x53, 0x65, 0x6c, 0x66, 0x1a, 0x44, 0x0a, 0x05, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22,
	0xa1, 0x04, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x05, 0x72, 0x70,
	0x63, 0x49, 0x64, 0x18, 0x85, 0x8e, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x70, 0x63,
	0x49, 0x64, 0x1a, 0xd9, 0x02, 0x0a, 0x13, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44,
	0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x55, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x55, 0x69, 0x64, 0x12, 0x52, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x1a, 0x32, 0x0a, 0x06, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x1a, 0x3b,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x1a, 0x56, 0x0a, 0x05, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x22, 0x9f, 0x02, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x05, 0x72,
	0x70, 0x63, 0x49, 0x64, 0x18, 0x86, 0x8e, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x70,
	0x63, 0x49, 0x64, 0x1a, 0xad, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x67, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x62,
	0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x1a, 0x40, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a, 0x08,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x08, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x22, 0xbf, 0x02, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a,
	0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x18, 0x87, 0x8e, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x72, 0x70, 0x63, 0x49, 0x64, 0x1a, 0xcd, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x65, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x40, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x37,
	0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x08, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x22, 0x85, 0x01, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12,
	0x16, 0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x18, 0x88, 0x8e, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x1a, 0x4d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x8c, 0x02, 0x0a, 0x13, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64,
	0x18, 0x89, 0x8e, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x1a,
	0x65, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x67, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x1a, 0x32, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x1a, 0x42, 0x0a, 0x05, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x39, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x55, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x86,
	0x01, 0x0a, 0x14, 0x53, 0x69, 0x67, 0x6e, 0x4f, 0x75, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64,
	0x18, 0x8a, 0x8e, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x1a,
	0x4d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x67, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x1a, 0x07,
	0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x8c, 0x01, 0x0a, 0x1a, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x18,
	0x8b, 0x8e, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x1a, 0x4d,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x67,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x1a, 0x07, 0x0a,
	0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x8d, 0x01, 0x0a, 0x1b, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x4f, 0x6e, 0x4d, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x18,
	0x8c, 0x8e, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x1a, 0x4d,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x67,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x1a, 0x07, 0x0a,
	0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x13, 0x5a, 0x11, 0x6c, 0x61, 0x69, 0x79, 0x61, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_outer_group_plugin_activity_proto_rawDescOnce sync.Once
	file_outer_group_plugin_activity_proto_rawDescData = file_outer_group_plugin_activity_proto_rawDesc
)

func file_outer_group_plugin_activity_proto_rawDescGZIP() []byte {
	file_outer_group_plugin_activity_proto_rawDescOnce.Do(func() {
		file_outer_group_plugin_activity_proto_rawDescData = protoimpl.X.CompressGZIP(file_outer_group_plugin_activity_proto_rawDescData)
	})
	return file_outer_group_plugin_activity_proto_rawDescData
}

var file_outer_group_plugin_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_outer_group_plugin_activity_proto_goTypes = []interface{}{
	(*GroupActivitySummary)(nil),                              // 0: outer.GroupActivitySummary
	(*GetGroupAllActivity)(nil),                               // 1: outer.GetGroupAllActivity
	(*GetGroupActivityDetail)(nil),                            // 2: outer.GetGroupActivityDetail
	(*CreateGroupActivity)(nil),                               // 3: outer.CreateGroupActivity
	(*UpdateGroupActivity)(nil),                               // 4: outer.UpdateGroupActivity
	(*DeleteGroupActivity)(nil),                               // 5: outer.DeleteGroupActivity
	(*SignUpGroupActivity)(nil),                               // 6: outer.SignUpGroupActivity
	(*SignOutGroupActivity)(nil),                              // 7: outer.SignOutGroupActivity
	(*BroadcastGroupActivityInfo)(nil),                        // 8: outer.BroadcastGroupActivityInfo
	(*BroadcastGroupActivityOnMic)(nil),                       // 9: outer.BroadcastGroupActivityOnMic
	(*GetGroupAllActivity_Request)(nil),                       // 10: outer.GetGroupAllActivity.Request
	(*GetGroupAllActivity_Reply)(nil),                         // 11: outer.GetGroupAllActivity.Reply
	(*GetGroupActivityDetail_GroupActivityDetail)(nil),        // 12: outer.GetGroupActivityDetail.GroupActivityDetail
	(*GetGroupActivityDetail_Request)(nil),                    // 13: outer.GetGroupActivityDetail.Request
	(*GetGroupActivityDetail_Reply)(nil),                      // 14: outer.GetGroupActivityDetail.Reply
	(*GetGroupActivityDetail_GroupActivityDetail_Player)(nil), // 15: outer.GetGroupActivityDetail.GroupActivityDetail.Player
	(*CreateGroupActivity_Request)(nil),                       // 16: outer.CreateGroupActivity.Request
	(*CreateGroupActivity_Reply)(nil),                         // 17: outer.CreateGroupActivity.Reply
	(*UpdateGroupActivity_Request)(nil),                       // 18: outer.UpdateGroupActivity.Request
	(*UpdateGroupActivity_Reply)(nil),                         // 19: outer.UpdateGroupActivity.Reply
	(*DeleteGroupActivity_Request)(nil),                       // 20: outer.DeleteGroupActivity.Request
	(*DeleteGroupActivity_Reply)(nil),                         // 21: outer.DeleteGroupActivity.Reply
	(*SignUpGroupActivity_Request)(nil),                       // 22: outer.SignUpGroupActivity.Request
	(*SignUpGroupActivity_Player)(nil),                        // 23: outer.SignUpGroupActivity.Player
	(*SignUpGroupActivity_Reply)(nil),                         // 24: outer.SignUpGroupActivity.Reply
	(*SignOutGroupActivity_Request)(nil),                      // 25: outer.SignOutGroupActivity.Request
	(*SignOutGroupActivity_Reply)(nil),                        // 26: outer.SignOutGroupActivity.Reply
	(*BroadcastGroupActivityInfo_Request)(nil),                // 27: outer.BroadcastGroupActivityInfo.Request
	(*BroadcastGroupActivityInfo_Reply)(nil),                  // 28: outer.BroadcastGroupActivityInfo.Reply
	(*BroadcastGroupActivityOnMic_Request)(nil),               // 29: outer.BroadcastGroupActivityOnMic.Request
	(*BroadcastGroupActivityOnMic_Reply)(nil),                 // 30: outer.BroadcastGroupActivityOnMic.Reply
}
var file_outer_group_plugin_activity_proto_depIdxs = []int32{
	0,  // 0: outer.GetGroupAllActivity.Reply.activities:type_name -> outer.GroupActivitySummary
	15, // 1: outer.GetGroupActivityDetail.GroupActivityDetail.players:type_name -> outer.GetGroupActivityDetail.GroupActivityDetail.Player
	12, // 2: outer.GetGroupActivityDetail.Reply.activity:type_name -> outer.GetGroupActivityDetail.GroupActivityDetail
	0,  // 3: outer.CreateGroupActivity.Reply.activity:type_name -> outer.GroupActivitySummary
	0,  // 4: outer.UpdateGroupActivity.Reply.activity:type_name -> outer.GroupActivitySummary
	23, // 5: outer.SignUpGroupActivity.Reply.player:type_name -> outer.SignUpGroupActivity.Player
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_outer_group_plugin_activity_proto_init() }
func file_outer_group_plugin_activity_proto_init() {
	if File_outer_group_plugin_activity_proto != nil {
		return
	}
	file_outer_outer_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_outer_group_plugin_activity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupActivitySummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupAllActivity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupActivityDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupActivity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGroupActivity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGroupActivity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpGroupActivity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignOutGroupActivity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastGroupActivityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastGroupActivityOnMic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupAllActivity_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupAllActivity_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupActivityDetail_GroupActivityDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupActivityDetail_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupActivityDetail_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupActivityDetail_GroupActivityDetail_Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupActivity_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupActivity_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGroupActivity_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGroupActivity_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGroupActivity_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGroupActivity_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpGroupActivity_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpGroupActivity_Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpGroupActivity_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignOutGroupActivity_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignOutGroupActivity_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastGroupActivityInfo_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastGroupActivityInfo_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastGroupActivityOnMic_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_group_plugin_activity_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastGroupActivityOnMic_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_outer_group_plugin_activity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outer_group_plugin_activity_proto_goTypes,
		DependencyIndexes: file_outer_group_plugin_activity_proto_depIdxs,
		MessageInfos:      file_outer_group_plugin_activity_proto_msgTypes,
	}.Build()
	File_outer_group_plugin_activity_proto = out.File
	file_outer_group_plugin_activity_proto_rawDesc = nil
	file_outer_group_plugin_activity_proto_goTypes = nil
	file_outer_group_plugin_activity_proto_depIdxs = nil
}
