// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.5.1
// source: outer/outer_common.proto

package outer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMsg_FromType int32

const (
	ChatMsg_UnknownFromType ChatMsg_FromType = 0 //未知
	ChatMsg_Friend          ChatMsg_FromType = 1 //私聊
	ChatMsg_Group           ChatMsg_FromType = 2 //群
)

// Enum value maps for ChatMsg_FromType.
var (
	ChatMsg_FromType_name = map[int32]string{
		0: "UnknownFromType",
		1: "Friend",
		2: "Group",
	}
	ChatMsg_FromType_value = map[string]int32{
		"UnknownFromType": 0,
		"Friend":          1,
		"Group":           2,
	}
)

func (x ChatMsg_FromType) Enum() *ChatMsg_FromType {
	p := new(ChatMsg_FromType)
	*p = x
	return p
}

func (x ChatMsg_FromType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMsg_FromType) Descriptor() protoreflect.EnumDescriptor {
	return file_outer_outer_common_proto_enumTypes[0].Descriptor()
}

func (ChatMsg_FromType) Type() protoreflect.EnumType {
	return &file_outer_outer_common_proto_enumTypes[0]
}

func (x ChatMsg_FromType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMsg_FromType.Descriptor instead.
func (ChatMsg_FromType) EnumDescriptor() ([]byte, []int) {
	return file_outer_outer_common_proto_rawDescGZIP(), []int{0, 0}
}

//内容类型
type ChatMsg_MsgType int32

const (
	ChatMsg_UnknownMsgType ChatMsg_MsgType = 0 //未知
	ChatMsg_Normal         ChatMsg_MsgType = 1 //普通聊天消息
	ChatMsg_CreateGroup    ChatMsg_MsgType = 2 //创建了群
	ChatMsg_FavoriteGroup  ChatMsg_MsgType = 3 //收藏了群
	ChatMsg_AddRobot       ChatMsg_MsgType = 4 //增加了机器人
	ChatMsg_RobotSay       ChatMsg_MsgType = 5 //机器人说话
	ChatMsg_Pic            ChatMsg_MsgType = 6 //图片消息
	ChatMsg_GroupActivity  ChatMsg_MsgType = 7 //群活动
)

// Enum value maps for ChatMsg_MsgType.
var (
	ChatMsg_MsgType_name = map[int32]string{
		0: "UnknownMsgType",
		1: "Normal",
		2: "CreateGroup",
		3: "FavoriteGroup",
		4: "AddRobot",
		5: "RobotSay",
		6: "Pic",
		7: "GroupActivity",
	}
	ChatMsg_MsgType_value = map[string]int32{
		"UnknownMsgType": 0,
		"Normal":         1,
		"CreateGroup":    2,
		"FavoriteGroup":  3,
		"AddRobot":       4,
		"RobotSay":       5,
		"Pic":            6,
		"GroupActivity":  7,
	}
)

func (x ChatMsg_MsgType) Enum() *ChatMsg_MsgType {
	p := new(ChatMsg_MsgType)
	*p = x
	return p
}

func (x ChatMsg_MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMsg_MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_outer_outer_common_proto_enumTypes[1].Descriptor()
}

func (ChatMsg_MsgType) Type() protoreflect.EnumType {
	return &file_outer_outer_common_proto_enumTypes[1]
}

func (x ChatMsg_MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMsg_MsgType.Descriptor instead.
func (ChatMsg_MsgType) EnumDescriptor() ([]byte, []int) {
	return file_outer_outer_common_proto_rawDescGZIP(), []int{0, 1}
}

type ChatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId    uint64           `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`                                   //消息连续自增id
	FromType ChatMsg_FromType `protobuf:"varint,2,opt,name=fromType,proto3,enum=outer.ChatMsg_FromType" json:"fromType,omitempty"` //消息来源类型
	MsgType  ChatMsg_MsgType  `protobuf:"varint,3,opt,name=msgType,proto3,enum=outer.ChatMsg_MsgType" json:"msgType,omitempty"`    //消息内容类型
	FromId   uint64           `protobuf:"varint,4,opt,name=fromId,proto3" json:"fromId,omitempty"`                                 //来源的id--私聊是发送方Id,群群消息是群id
	SenderId uint64           `protobuf:"varint,5,opt,name=senderId,proto3" json:"senderId,omitempty"`                             //消息发送者的Id--私聊是发送放Id,群消息也是发送方id
	ToId     uint64           `protobuf:"varint,6,opt,name=toId,proto3" json:"toId,omitempty"`                                     //发送给谁
	Time     int64            `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`                                     //发送时间
	Content  *anypb.Any       `protobuf:"bytes,8,opt,name=Content,proto3" json:"Content,omitempty"`                                //消息内容--内部有个TypeUrl--标记了数据类型
	At       []uint64         `protobuf:"varint,9,rep,packed,name=at,proto3" json:"at,omitempty"`                                  //@的对象 注: 0表示@全部
	Uuid     uint64           `protobuf:"varint,10,opt,name=uuid,proto3" json:"uuid,omitempty"`                                    //唯一id
	RId      uint64           `protobuf:"varint,11,opt,name=rId,proto3" json:"rId,omitempty"`                                      //客户端的roomId(群聊取群id，私聊为对方的uid)，对服务器来说无意义，纯客户但使用
}

func (x *ChatMsg) Reset() {
	*x = ChatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_outer_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg) ProtoMessage() {}

func (x *ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_outer_outer_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return file_outer_outer_common_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMsg) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ChatMsg) GetFromType() ChatMsg_FromType {
	if x != nil {
		return x.FromType
	}
	return ChatMsg_UnknownFromType
}

func (x *ChatMsg) GetMsgType() ChatMsg_MsgType {
	if x != nil {
		return x.MsgType
	}
	return ChatMsg_UnknownMsgType
}

func (x *ChatMsg) GetFromId() uint64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *ChatMsg) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMsg) GetToId() uint64 {
	if x != nil {
		return x.ToId
	}
	return 0
}

func (x *ChatMsg) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ChatMsg) GetContent() *anypb.Any {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ChatMsg) GetAt() []uint64 {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *ChatMsg) GetUuid() uint64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *ChatMsg) GetRId() uint64 {
	if x != nil {
		return x.RId
	}
	return 0
}

//普通聊天消息
type ChatMsg_NormalMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text       string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	SenderName string `protobuf:"bytes,2,opt,name=senderName,proto3" json:"senderName,omitempty"` //发送者的名字(群聊才有)--临时协议,后续客户端有缓存更新方案后，这里要去掉
	SenderIcon string `protobuf:"bytes,3,opt,name=senderIcon,proto3" json:"senderIcon,omitempty"` //发送者的icon(群聊才有)--临时协议,后续客户端有缓存更新方案后，这里要去掉
}

func (x *ChatMsg_NormalMsg) Reset() {
	*x = ChatMsg_NormalMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_outer_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsg_NormalMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg_NormalMsg) ProtoMessage() {}

func (x *ChatMsg_NormalMsg) ProtoReflect() protoreflect.Message {
	mi := &file_outer_outer_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg_NormalMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg_NormalMsg) Descriptor() ([]byte, []int) {
	return file_outer_outer_common_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ChatMsg_NormalMsg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMsg_NormalMsg) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ChatMsg_NormalMsg) GetSenderIcon() string {
	if x != nil {
		return x.SenderIcon
	}
	return ""
}

//用户创建群
type ChatMsg_CreateGroupMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *ChatMsg_CreateGroupMsg) Reset() {
	*x = ChatMsg_CreateGroupMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_outer_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsg_CreateGroupMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg_CreateGroupMsg) ProtoMessage() {}

func (x *ChatMsg_CreateGroupMsg) ProtoReflect() protoreflect.Message {
	mi := &file_outer_outer_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg_CreateGroupMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg_CreateGroupMsg) Descriptor() ([]byte, []int) {
	return file_outer_outer_common_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ChatMsg_CreateGroupMsg) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

//用户收藏了群
type ChatMsg_FavoriteGroupMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *ChatMsg_FavoriteGroupMsg) Reset() {
	*x = ChatMsg_FavoriteGroupMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_outer_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsg_FavoriteGroupMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg_FavoriteGroupMsg) ProtoMessage() {}

func (x *ChatMsg_FavoriteGroupMsg) ProtoReflect() protoreflect.Message {
	mi := &file_outer_outer_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg_FavoriteGroupMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg_FavoriteGroupMsg) Descriptor() ([]byte, []int) {
	return file_outer_outer_common_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ChatMsg_FavoriteGroupMsg) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

//增加了机器人
type ChatMsg_AddRobotMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId   uint64 `protobuf:"varint,1,opt,name=robotId,proto3" json:"robotId,omitempty"`    //机器人id
	RobotName string `protobuf:"bytes,2,opt,name=robotName,proto3" json:"robotName,omitempty"` //机器人名字
	RobotIcon string `protobuf:"bytes,3,opt,name=robotIcon,proto3" json:"robotIcon,omitempty"` //机器人icon
}

func (x *ChatMsg_AddRobotMsg) Reset() {
	*x = ChatMsg_AddRobotMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_outer_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsg_AddRobotMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg_AddRobotMsg) ProtoMessage() {}

func (x *ChatMsg_AddRobotMsg) ProtoReflect() protoreflect.Message {
	mi := &file_outer_outer_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg_AddRobotMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg_AddRobotMsg) Descriptor() ([]byte, []int) {
	return file_outer_outer_common_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ChatMsg_AddRobotMsg) GetRobotId() uint64 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *ChatMsg_AddRobotMsg) GetRobotName() string {
	if x != nil {
		return x.RobotName
	}
	return ""
}

func (x *ChatMsg_AddRobotMsg) GetRobotIcon() string {
	if x != nil {
		return x.RobotIcon
	}
	return ""
}

//
type ChatMsg_RobotSayMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text       string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	SenderName string `protobuf:"bytes,2,opt,name=senderName,proto3" json:"senderName,omitempty"` //发送者的名字--临时协议,后续客户端有缓存更新方案后，这里要去掉
	SenderIcon string `protobuf:"bytes,3,opt,name=senderIcon,proto3" json:"senderIcon,omitempty"` //发送者的icon--临时协议,后续客户端有缓存更新方案后，这里要去掉
}

func (x *ChatMsg_RobotSayMsg) Reset() {
	*x = ChatMsg_RobotSayMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_outer_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsg_RobotSayMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg_RobotSayMsg) ProtoMessage() {}

func (x *ChatMsg_RobotSayMsg) ProtoReflect() protoreflect.Message {
	mi := &file_outer_outer_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg_RobotSayMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg_RobotSayMsg) Descriptor() ([]byte, []int) {
	return file_outer_outer_common_proto_rawDescGZIP(), []int{0, 4}
}

func (x *ChatMsg_RobotSayMsg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMsg_RobotSayMsg) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ChatMsg_RobotSayMsg) GetSenderIcon() string {
	if x != nil {
		return x.SenderIcon
	}
	return ""
}

//
type ChatMsg_PicMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url        string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`               //图片地址
	SenderName string `protobuf:"bytes,2,opt,name=senderName,proto3" json:"senderName,omitempty"` //发送者的名字(群聊才有)--临时协议,后续客户端有缓存更新方案后，这里要去掉
	SenderIcon string `protobuf:"bytes,3,opt,name=senderIcon,proto3" json:"senderIcon,omitempty"` //发送者的icon(群聊才有)--临时协议,后续客户端有缓存更新方案后，这里要去掉
}

func (x *ChatMsg_PicMsg) Reset() {
	*x = ChatMsg_PicMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_outer_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsg_PicMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg_PicMsg) ProtoMessage() {}

func (x *ChatMsg_PicMsg) ProtoReflect() protoreflect.Message {
	mi := &file_outer_outer_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg_PicMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg_PicMsg) Descriptor() ([]byte, []int) {
	return file_outer_outer_common_proto_rawDescGZIP(), []int{0, 5}
}

func (x *ChatMsg_PicMsg) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ChatMsg_PicMsg) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ChatMsg_PicMsg) GetSenderIcon() string {
	if x != nil {
		return x.SenderIcon
	}
	return ""
}

//
type ChatMsg_GroupActivityMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderName    string `protobuf:"bytes,1,opt,name=senderName,proto3" json:"senderName,omitempty"`       //发送者的名字(群聊才有)--临时协议,后续客户端有缓存更新方案后，这里要去掉
	SenderIcon    string `protobuf:"bytes,2,opt,name=senderIcon,proto3" json:"senderIcon,omitempty"`       //发送者的icon(群聊才有)--临时协议,后续客户端有缓存更新方案后，这里要去掉
	ActivityId    uint64 `protobuf:"varint,3,opt,name=activityId,proto3" json:"activityId,omitempty"`      //活动id
	ActivityTitle string `protobuf:"bytes,4,opt,name=activityTitle,proto3" json:"activityTitle,omitempty"` //活动标题
	BeginTime     int64  `protobuf:"varint,5,opt,name=beginTime,proto3" json:"beginTime,omitempty"`        //开始时间戳
	EndTime       int64  `protobuf:"varint,6,opt,name=endTime,proto3" json:"endTime,omitempty"`            //结束时间戳
}

func (x *ChatMsg_GroupActivityMsg) Reset() {
	*x = ChatMsg_GroupActivityMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_outer_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsg_GroupActivityMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg_GroupActivityMsg) ProtoMessage() {}

func (x *ChatMsg_GroupActivityMsg) ProtoReflect() protoreflect.Message {
	mi := &file_outer_outer_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg_GroupActivityMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg_GroupActivityMsg) Descriptor() ([]byte, []int) {
	return file_outer_outer_common_proto_rawDescGZIP(), []int{0, 6}
}

func (x *ChatMsg_GroupActivityMsg) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ChatMsg_GroupActivityMsg) GetSenderIcon() string {
	if x != nil {
		return x.SenderIcon
	}
	return ""
}

func (x *ChatMsg_GroupActivityMsg) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ChatMsg_GroupActivityMsg) GetActivityTitle() string {
	if x != nil {
		return x.ActivityTitle
	}
	return ""
}

func (x *ChatMsg_GroupActivityMsg) GetBeginTime() int64 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *ChatMsg_GroupActivityMsg) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

var File_outer_outer_common_proto protoreflect.FileDescriptor

var file_outer_outer_common_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbe, 0x09, 0x0a,
	0x07, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x33,
	0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x17, 0x2e, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67,
	0x2e, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61,
	0x74, 0x4d, 0x73, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x6f, 0x49,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x2e, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x61, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x04, 0x52, 0x02, 0x61,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x72, 0x49, 0x64, 0x1a, 0x5f, 0x0a, 0x09, 0x4e, 0x6f, 0x72, 0x6d, 0x61,
	0x6c, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x49, 0x63, 0x6f, 0x6e, 0x1a, 0x2c, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x2e, 0x0a, 0x10, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x63, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x62,
	0x6f, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x1a, 0x61, 0x0a, 0x0b, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x53, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x63, 0x6f, 0x6e, 0x1a, 0x5a,
	0x0a, 0x06, 0x50, 0x69, 0x63, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x63, 0x6f, 0x6e, 0x1a, 0xd0, 0x01, 0x0a, 0x10, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x63, 0x6f, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x36, 0x0a,
	0x08, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x10, 0x02, 0x22, 0x85, 0x01, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x4d, 0x73, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10,
	0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x62, 0x6f,
	0x74, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x53, 0x61, 0x79, 0x10,
	0x05, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x69, 0x63, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x10, 0x07, 0x42, 0x13, 0x5a,
	0x11, 0x6c, 0x61, 0x69, 0x79, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_outer_outer_common_proto_rawDescOnce sync.Once
	file_outer_outer_common_proto_rawDescData = file_outer_outer_common_proto_rawDesc
)

func file_outer_outer_common_proto_rawDescGZIP() []byte {
	file_outer_outer_common_proto_rawDescOnce.Do(func() {
		file_outer_outer_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_outer_outer_common_proto_rawDescData)
	})
	return file_outer_outer_common_proto_rawDescData
}

var file_outer_outer_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_outer_outer_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_outer_outer_common_proto_goTypes = []interface{}{
	(ChatMsg_FromType)(0),            // 0: outer.ChatMsg.FromType
	(ChatMsg_MsgType)(0),             // 1: outer.ChatMsg.MsgType
	(*ChatMsg)(nil),                  // 2: outer.ChatMsg
	(*ChatMsg_NormalMsg)(nil),        // 3: outer.ChatMsg.NormalMsg
	(*ChatMsg_CreateGroupMsg)(nil),   // 4: outer.ChatMsg.CreateGroupMsg
	(*ChatMsg_FavoriteGroupMsg)(nil), // 5: outer.ChatMsg.FavoriteGroupMsg
	(*ChatMsg_AddRobotMsg)(nil),      // 6: outer.ChatMsg.AddRobotMsg
	(*ChatMsg_RobotSayMsg)(nil),      // 7: outer.ChatMsg.RobotSayMsg
	(*ChatMsg_PicMsg)(nil),           // 8: outer.ChatMsg.PicMsg
	(*ChatMsg_GroupActivityMsg)(nil), // 9: outer.ChatMsg.GroupActivityMsg
	(*anypb.Any)(nil),                // 10: google.protobuf.Any
}
var file_outer_outer_common_proto_depIdxs = []int32{
	0,  // 0: outer.ChatMsg.fromType:type_name -> outer.ChatMsg.FromType
	1,  // 1: outer.ChatMsg.msgType:type_name -> outer.ChatMsg.MsgType
	10, // 2: outer.ChatMsg.Content:type_name -> google.protobuf.Any
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_outer_outer_common_proto_init() }
func file_outer_outer_common_proto_init() {
	if File_outer_outer_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_outer_outer_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_outer_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsg_NormalMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_outer_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsg_CreateGroupMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_outer_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsg_FavoriteGroupMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_outer_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsg_AddRobotMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_outer_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsg_RobotSayMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_outer_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsg_PicMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_outer_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsg_GroupActivityMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_outer_outer_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outer_outer_common_proto_goTypes,
		DependencyIndexes: file_outer_outer_common_proto_depIdxs,
		EnumInfos:         file_outer_outer_common_proto_enumTypes,
		MessageInfos:      file_outer_outer_common_proto_msgTypes,
	}.Build()
	File_outer_outer_common_proto = out.File
	file_outer_outer_common_proto_rawDesc = nil
	file_outer_outer_common_proto_goTypes = nil
	file_outer_outer_common_proto_depIdxs = nil
}
