// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.5.1
// source: outer/web.proto

package outer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebLoginUseInfo_State int32

const (
	WebLoginUseInfo_Unknown    WebLoginUseInfo_State = 0 //未知
	WebLoginUseInfo_Registered WebLoginUseInfo_State = 1 // 已注册用户
	WebLoginUseInfo_New        WebLoginUseInfo_State = 2 // 新用户
	WebLoginUseInfo_Old        WebLoginUseInfo_State = 3 // 继承用户--登录成功后会变为 Registered
)

// Enum value maps for WebLoginUseInfo_State.
var (
	WebLoginUseInfo_State_name = map[int32]string{
		0: "Unknown",
		1: "Registered",
		2: "New",
		3: "Old",
	}
	WebLoginUseInfo_State_value = map[string]int32{
		"Unknown":    0,
		"Registered": 1,
		"New":        2,
		"Old":        3,
	}
)

func (x WebLoginUseInfo_State) Enum() *WebLoginUseInfo_State {
	p := new(WebLoginUseInfo_State)
	*p = x
	return p
}

func (x WebLoginUseInfo_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebLoginUseInfo_State) Descriptor() protoreflect.EnumDescriptor {
	return file_outer_web_proto_enumTypes[0].Descriptor()
}

func (WebLoginUseInfo_State) Type() protoreflect.EnumType {
	return &file_outer_web_proto_enumTypes[0]
}

func (x WebLoginUseInfo_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebLoginUseInfo_State.Descriptor instead.
func (WebLoginUseInfo_State) EnumDescriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{1, 0}
}

type UploadIcon_IconType int32

const (
	UploadIcon_Unknown   UploadIcon_IconType = 0 //未知
	UploadIcon_Head      UploadIcon_IconType = 1 //头像
	UploadIcon_GroupHead UploadIcon_IconType = 2 //群头像
	UploadIcon_ChatPic   UploadIcon_IconType = 3 //聊天图片
)

// Enum value maps for UploadIcon_IconType.
var (
	UploadIcon_IconType_name = map[int32]string{
		0: "Unknown",
		1: "Head",
		2: "GroupHead",
		3: "ChatPic",
	}
	UploadIcon_IconType_value = map[string]int32{
		"Unknown":   0,
		"Head":      1,
		"GroupHead": 2,
		"ChatPic":   3,
	}
)

func (x UploadIcon_IconType) Enum() *UploadIcon_IconType {
	p := new(UploadIcon_IconType)
	*p = x
	return p
}

func (x UploadIcon_IconType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadIcon_IconType) Descriptor() protoreflect.EnumDescriptor {
	return file_outer_web_proto_enumTypes[1].Descriptor()
}

func (UploadIcon_IconType) Type() protoreflect.EnumType {
	return &file_outer_web_proto_enumTypes[1]
}

func (x UploadIcon_IconType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadIcon_IconType.Descriptor instead.
func (UploadIcon_IconType) EnumDescriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{4, 0}
}

//获取验证码
type GetCaptcha struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,20000,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *GetCaptcha) Reset() {
	*x = GetCaptcha{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCaptcha) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptcha) ProtoMessage() {}

func (x *GetCaptcha) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptcha.ProtoReflect.Descriptor instead.
func (*GetCaptcha) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{0}
}

func (x *GetCaptcha) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//web登录返回的用户数据
type WebLoginUseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WebLoginUseInfo) Reset() {
	*x = WebLoginUseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebLoginUseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebLoginUseInfo) ProtoMessage() {}

func (x *WebLoginUseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebLoginUseInfo.ProtoReflect.Descriptor instead.
func (*WebLoginUseInfo) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{1}
}

//校验验证码
type CheckCaptcha struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,20001,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *CheckCaptcha) Reset() {
	*x = CheckCaptcha{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckCaptcha) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCaptcha) ProtoMessage() {}

func (x *CheckCaptcha) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCaptcha.ProtoReflect.Descriptor instead.
func (*CheckCaptcha) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{2}
}

func (x *CheckCaptcha) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//校验token
type CheckToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,20003,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *CheckToken) Reset() {
	*x = CheckToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckToken) ProtoMessage() {}

func (x *CheckToken) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckToken.ProtoReflect.Descriptor instead.
func (*CheckToken) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{3}
}

func (x *CheckToken) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//上传Icon
type UploadIcon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,20004,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *UploadIcon) Reset() {
	*x = UploadIcon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadIcon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadIcon) ProtoMessage() {}

func (x *UploadIcon) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadIcon.ProtoReflect.Descriptor instead.
func (*UploadIcon) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{4}
}

func (x *UploadIcon) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//获取游戏类型
type GetGameTypes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,20005,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *GetGameTypes) Reset() {
	*x = GetGameTypes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameTypes) ProtoMessage() {}

func (x *GetGameTypes) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameTypes.ProtoReflect.Descriptor instead.
func (*GetGameTypes) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{5}
}

func (x *GetGameTypes) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//
type DeleteAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,20006,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *DeleteAccount) Reset() {
	*x = DeleteAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccount) ProtoMessage() {}

func (x *DeleteAccount) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccount.ProtoReflect.Descriptor instead.
func (*DeleteAccount) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAccount) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//客户端版本号检查
type CheckClientVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,20010,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *CheckClientVersion) Reset() {
	*x = CheckClientVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckClientVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckClientVersion) ProtoMessage() {}

func (x *CheckClientVersion) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckClientVersion.ProtoReflect.Descriptor instead.
func (*CheckClientVersion) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{7}
}

func (x *CheckClientVersion) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//获取机器人信息
type GetRobotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,20020,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *GetRobotInfo) Reset() {
	*x = GetRobotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRobotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRobotInfo) ProtoMessage() {}

func (x *GetRobotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRobotInfo.ProtoReflect.Descriptor instead.
func (*GetRobotInfo) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{8}
}

func (x *GetRobotInfo) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

//增加或修改机器人信息
type UpdateRobotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,20021,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
}

func (x *UpdateRobotInfo) Reset() {
	*x = UpdateRobotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRobotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRobotInfo) ProtoMessage() {}

func (x *UpdateRobotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRobotInfo.ProtoReflect.Descriptor instead.
func (*UpdateRobotInfo) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRobotInfo) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

type GetCaptcha_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ph string `protobuf:"bytes,1,opt,name=ph,proto3" json:"ph,omitempty"`
}

func (x *GetCaptcha_Request) Reset() {
	*x = GetCaptcha_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCaptcha_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptcha_Request) ProtoMessage() {}

func (x *GetCaptcha_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptcha_Request.ProtoReflect.Descriptor instead.
func (*GetCaptcha_Request) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetCaptcha_Request) GetPh() string {
	if x != nil {
		return x.Ph
	}
	return ""
}

type GetCaptcha_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCaptcha_Reply) Reset() {
	*x = GetCaptcha_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCaptcha_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptcha_Reply) ProtoMessage() {}

func (x *GetCaptcha_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptcha_Reply.ProtoReflect.Descriptor instead.
func (*GetCaptcha_Reply) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{0, 1}
}

type WebLoginUseInfo_UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid   uint64                `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name  string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon  string                `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Des   string                `protobuf:"bytes,4,opt,name=des,proto3" json:"des,omitempty"`                                       //用户描述
	State WebLoginUseInfo_State `protobuf:"varint,5,opt,name=state,proto3,enum=outer.WebLoginUseInfo_State" json:"state,omitempty"` //用户状态
}

func (x *WebLoginUseInfo_UserInfo) Reset() {
	*x = WebLoginUseInfo_UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebLoginUseInfo_UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebLoginUseInfo_UserInfo) ProtoMessage() {}

func (x *WebLoginUseInfo_UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebLoginUseInfo_UserInfo.ProtoReflect.Descriptor instead.
func (*WebLoginUseInfo_UserInfo) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{1, 0}
}

func (x *WebLoginUseInfo_UserInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *WebLoginUseInfo_UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebLoginUseInfo_UserInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *WebLoginUseInfo_UserInfo) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

func (x *WebLoginUseInfo_UserInfo) GetState() WebLoginUseInfo_State {
	if x != nil {
		return x.State
	}
	return WebLoginUseInfo_Unknown
}

type CheckCaptcha_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ph      string `protobuf:"bytes,1,opt,name=ph,proto3" json:"ph,omitempty"`
	Captcha string `protobuf:"bytes,2,opt,name=captcha,proto3" json:"captcha,omitempty"`
}

func (x *CheckCaptcha_Request) Reset() {
	*x = CheckCaptcha_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckCaptcha_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCaptcha_Request) ProtoMessage() {}

func (x *CheckCaptcha_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCaptcha_Request.ProtoReflect.Descriptor instead.
func (*CheckCaptcha_Request) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CheckCaptcha_Request) GetPh() string {
	if x != nil {
		return x.Ph
	}
	return ""
}

func (x *CheckCaptcha_Request) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type CheckCaptcha_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string                    `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserInfo *WebLoginUseInfo_UserInfo `protobuf:"bytes,2,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
}

func (x *CheckCaptcha_Reply) Reset() {
	*x = CheckCaptcha_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckCaptcha_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCaptcha_Reply) ProtoMessage() {}

func (x *CheckCaptcha_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCaptcha_Reply.ProtoReflect.Descriptor instead.
func (*CheckCaptcha_Reply) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{2, 1}
}

func (x *CheckCaptcha_Reply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CheckCaptcha_Reply) GetUserInfo() *WebLoginUseInfo_UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type CheckToken_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtoVersion int64 `protobuf:"varint,1,opt,name=protoVersion,proto3" json:"protoVersion,omitempty"` //客户端协议版本号--
}

func (x *CheckToken_Request) Reset() {
	*x = CheckToken_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckToken_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckToken_Request) ProtoMessage() {}

func (x *CheckToken_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckToken_Request.ProtoReflect.Descriptor instead.
func (*CheckToken_Request) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CheckToken_Request) GetProtoVersion() int64 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

type CheckToken_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckToken_Reply) Reset() {
	*x = CheckToken_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckToken_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckToken_Reply) ProtoMessage() {}

func (x *CheckToken_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckToken_Reply.ProtoReflect.Descriptor instead.
func (*CheckToken_Reply) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{3, 1}
}

//http的body格式为form-data
//type字段值为Head GroupHead 等IconType
//icon字段为上传的文件
type UploadIcon_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UploadIcon_Request) Reset() {
	*x = UploadIcon_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadIcon_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadIcon_Request) ProtoMessage() {}

func (x *UploadIcon_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadIcon_Request.ProtoReflect.Descriptor instead.
func (*UploadIcon_Request) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{4, 0}
}

type UploadIcon_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *UploadIcon_Reply) Reset() {
	*x = UploadIcon_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadIcon_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadIcon_Reply) ProtoMessage() {}

func (x *UploadIcon_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadIcon_Reply.ProtoReflect.Descriptor instead.
func (*UploadIcon_Reply) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{4, 1}
}

func (x *UploadIcon_Reply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetGameTypes_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGameTypes_Request) Reset() {
	*x = GetGameTypes_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameTypes_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameTypes_Request) ProtoMessage() {}

func (x *GetGameTypes_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameTypes_Request.ProtoReflect.Descriptor instead.
func (*GetGameTypes_Request) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{5, 0}
}

type GetGameTypes_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameTypes []string `protobuf:"bytes,1,rep,name=gameTypes,proto3" json:"gameTypes,omitempty"`
}

func (x *GetGameTypes_Reply) Reset() {
	*x = GetGameTypes_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameTypes_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameTypes_Reply) ProtoMessage() {}

func (x *GetGameTypes_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameTypes_Reply.ProtoReflect.Descriptor instead.
func (*GetGameTypes_Reply) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{5, 1}
}

func (x *GetGameTypes_Reply) GetGameTypes() []string {
	if x != nil {
		return x.GameTypes
	}
	return nil
}

type DeleteAccount_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *DeleteAccount_Request) Reset() {
	*x = DeleteAccount_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAccount_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccount_Request) ProtoMessage() {}

func (x *DeleteAccount_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccount_Request.ProtoReflect.Descriptor instead.
func (*DeleteAccount_Request) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{6, 0}
}

func (x *DeleteAccount_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type DeleteAccount_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAccount_Reply) Reset() {
	*x = DeleteAccount_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAccount_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccount_Reply) ProtoMessage() {}

func (x *DeleteAccount_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccount_Reply.ProtoReflect.Descriptor instead.
func (*DeleteAccount_Reply) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{6, 1}
}

type CheckClientVersion_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientVersion string `protobuf:"bytes,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
}

func (x *CheckClientVersion_Request) Reset() {
	*x = CheckClientVersion_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckClientVersion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckClientVersion_Request) ProtoMessage() {}

func (x *CheckClientVersion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckClientVersion_Request.ProtoReflect.Descriptor instead.
func (*CheckClientVersion_Request) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{7, 0}
}

func (x *CheckClientVersion_Request) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type CheckClientVersion_Version struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` //版本号
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`     //新版本标题
	Detail  string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`   //新版本详情
}

func (x *CheckClientVersion_Version) Reset() {
	*x = CheckClientVersion_Version{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckClientVersion_Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckClientVersion_Version) ProtoMessage() {}

func (x *CheckClientVersion_Version) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckClientVersion_Version.ProtoReflect.Descriptor instead.
func (*CheckClientVersion_Version) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{7, 1}
}

func (x *CheckClientVersion_Version) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CheckClientVersion_Version) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CheckClientVersion_Version) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type CheckClientVersion_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VersionAvailable bool                        `protobuf:"varint,1,opt,name=versionAvailable,proto3" json:"versionAvailable,omitempty"` //false表示当前版本已经废弃
	LastVersion      *CheckClientVersion_Version `protobuf:"bytes,2,opt,name=lastVersion,proto3" json:"lastVersion,omitempty"`            //有新版本时候有值
}

func (x *CheckClientVersion_Reply) Reset() {
	*x = CheckClientVersion_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckClientVersion_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckClientVersion_Reply) ProtoMessage() {}

func (x *CheckClientVersion_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckClientVersion_Reply.ProtoReflect.Descriptor instead.
func (*CheckClientVersion_Reply) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{7, 2}
}

func (x *CheckClientVersion_Reply) GetVersionAvailable() bool {
	if x != nil {
		return x.VersionAvailable
	}
	return false
}

func (x *CheckClientVersion_Reply) GetLastVersion() *CheckClientVersion_Version {
	if x != nil {
		return x.LastVersion
	}
	return nil
}

type GetRobotInfo_RobotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon string `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Des  string `protobuf:"bytes,4,opt,name=des,proto3" json:"des,omitempty"` //用户描述
}

func (x *GetRobotInfo_RobotInfo) Reset() {
	*x = GetRobotInfo_RobotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRobotInfo_RobotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRobotInfo_RobotInfo) ProtoMessage() {}

func (x *GetRobotInfo_RobotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRobotInfo_RobotInfo.ProtoReflect.Descriptor instead.
func (*GetRobotInfo_RobotInfo) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{8, 0}
}

func (x *GetRobotInfo_RobotInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetRobotInfo_RobotInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRobotInfo_RobotInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *GetRobotInfo_RobotInfo) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type GetRobotInfo_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetRobotInfo_Request) Reset() {
	*x = GetRobotInfo_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRobotInfo_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRobotInfo_Request) ProtoMessage() {}

func (x *GetRobotInfo_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRobotInfo_Request.ProtoReflect.Descriptor instead.
func (*GetRobotInfo_Request) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{8, 1}
}

func (x *GetRobotInfo_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetRobotInfo_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotInfo *GetRobotInfo_RobotInfo `protobuf:"bytes,1,opt,name=robotInfo,proto3" json:"robotInfo,omitempty"`
}

func (x *GetRobotInfo_Reply) Reset() {
	*x = GetRobotInfo_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRobotInfo_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRobotInfo_Reply) ProtoMessage() {}

func (x *GetRobotInfo_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRobotInfo_Reply.ProtoReflect.Descriptor instead.
func (*GetRobotInfo_Reply) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{8, 2}
}

func (x *GetRobotInfo_Reply) GetRobotInfo() *GetRobotInfo_RobotInfo {
	if x != nil {
		return x.RobotInfo
	}
	return nil
}

type UpdateRobotInfo_RobotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon string `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Des  string `protobuf:"bytes,4,opt,name=des,proto3" json:"des,omitempty"` //用户描述
}

func (x *UpdateRobotInfo_RobotInfo) Reset() {
	*x = UpdateRobotInfo_RobotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRobotInfo_RobotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRobotInfo_RobotInfo) ProtoMessage() {}

func (x *UpdateRobotInfo_RobotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRobotInfo_RobotInfo.ProtoReflect.Descriptor instead.
func (*UpdateRobotInfo_RobotInfo) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{9, 0}
}

func (x *UpdateRobotInfo_RobotInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateRobotInfo_RobotInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRobotInfo_RobotInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateRobotInfo_RobotInfo) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type UpdateRobotInfo_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotInfo *UpdateRobotInfo_RobotInfo `protobuf:"bytes,1,opt,name=robotInfo,proto3" json:"robotInfo,omitempty"`
}

func (x *UpdateRobotInfo_Request) Reset() {
	*x = UpdateRobotInfo_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRobotInfo_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRobotInfo_Request) ProtoMessage() {}

func (x *UpdateRobotInfo_Request) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRobotInfo_Request.ProtoReflect.Descriptor instead.
func (*UpdateRobotInfo_Request) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{9, 1}
}

func (x *UpdateRobotInfo_Request) GetRobotInfo() *UpdateRobotInfo_RobotInfo {
	if x != nil {
		return x.RobotInfo
	}
	return nil
}

type UpdateRobotInfo_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateRobotInfo_Reply) Reset() {
	*x = UpdateRobotInfo_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outer_web_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRobotInfo_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRobotInfo_Reply) ProtoMessage() {}

func (x *UpdateRobotInfo_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_outer_web_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRobotInfo_Reply.ProtoReflect.Descriptor instead.
func (*UpdateRobotInfo_Reply) Descriptor() ([]byte, []int) {
	return file_outer_web_proto_rawDescGZIP(), []int{9, 2}
}

var File_outer_web_proto protoreflect.FileDescriptor

var file_outer_web_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x77, 0x65, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x22, 0x48, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x12, 0x16, 0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x18,
	0xa0, 0x9c, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x1a, 0x19,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x70, 0x68, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0xd6, 0x01, 0x0a, 0x0f, 0x57, 0x65, 0x62, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55,
	0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x8a, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x12,
	0x32, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x57, 0x65, 0x62, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55,
	0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x36, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x65, 0x77,
	0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x6c, 0x64, 0x10, 0x03, 0x22, 0xb7, 0x01, 0x0a, 0x0c,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x12, 0x16, 0x0a, 0x05,
	0x72, 0x70, 0x63, 0x49, 0x64, 0x18, 0xa1, 0x9c, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72,
	0x70, 0x63, 0x49, 0x64, 0x1a, 0x33, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x70, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x70, 0x68, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x1a, 0x5a, 0x0a, 0x05, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3b, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x2e, 0x57, 0x65, 0x62, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x5c, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x18, 0xa3, 0x9c, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x1a, 0x2d, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x89, 0x01, 0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x63,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x18, 0xa4, 0x9c, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x22, 0x3d, 0x0a, 0x08, 0x49, 0x63, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x65, 0x61,
	0x64, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x48, 0x65, 0x61, 0x64,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x50, 0x69, 0x63, 0x10, 0x03, 0x22,
	0x58, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12,
	0x16, 0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x18, 0xa5, 0x9c, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x67,
	0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x0d, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x72, 0x70,
	0x63, 0x49, 0x64, 0x18, 0xa6, 0x9c, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x70, 0x63,
	0x49, 0x64, 0x1a, 0x1b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x1a,
	0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0xaa, 0x02, 0x0a, 0x12, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x18, 0xaa, 0x9c, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x1a, 0x2f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x51, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x1a, 0x78, 0x0a, 0x05, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x10, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x43, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xe2, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x62,
	0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x18,
	0xb4, 0x9c, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x1a, 0x57,
	0x0a, 0x09, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x1a, 0x1b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x1a, 0x44, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a,
	0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x62, 0x6f,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xd6, 0x01, 0x0a, 0x0f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x18, 0xb5, 0x9c, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x1a, 0x57, 0x0a, 0x09, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x1a,
	0x49, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x09, 0x72, 0x6f,
	0x62, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x62, 0x6f,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x13, 0x5a, 0x11, 0x6c, 0x61, 0x69, 0x79, 0x61, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_outer_web_proto_rawDescOnce sync.Once
	file_outer_web_proto_rawDescData = file_outer_web_proto_rawDesc
)

func file_outer_web_proto_rawDescGZIP() []byte {
	file_outer_web_proto_rawDescOnce.Do(func() {
		file_outer_web_proto_rawDescData = protoimpl.X.CompressGZIP(file_outer_web_proto_rawDescData)
	})
	return file_outer_web_proto_rawDescData
}

var file_outer_web_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_outer_web_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_outer_web_proto_goTypes = []interface{}{
	(WebLoginUseInfo_State)(0),         // 0: outer.WebLoginUseInfo.State
	(UploadIcon_IconType)(0),           // 1: outer.UploadIcon.IconType
	(*GetCaptcha)(nil),                 // 2: outer.GetCaptcha
	(*WebLoginUseInfo)(nil),            // 3: outer.WebLoginUseInfo
	(*CheckCaptcha)(nil),               // 4: outer.CheckCaptcha
	(*CheckToken)(nil),                 // 5: outer.CheckToken
	(*UploadIcon)(nil),                 // 6: outer.UploadIcon
	(*GetGameTypes)(nil),               // 7: outer.GetGameTypes
	(*DeleteAccount)(nil),              // 8: outer.DeleteAccount
	(*CheckClientVersion)(nil),         // 9: outer.CheckClientVersion
	(*GetRobotInfo)(nil),               // 10: outer.GetRobotInfo
	(*UpdateRobotInfo)(nil),            // 11: outer.UpdateRobotInfo
	(*GetCaptcha_Request)(nil),         // 12: outer.GetCaptcha.Request
	(*GetCaptcha_Reply)(nil),           // 13: outer.GetCaptcha.Reply
	(*WebLoginUseInfo_UserInfo)(nil),   // 14: outer.WebLoginUseInfo.UserInfo
	(*CheckCaptcha_Request)(nil),       // 15: outer.CheckCaptcha.Request
	(*CheckCaptcha_Reply)(nil),         // 16: outer.CheckCaptcha.Reply
	(*CheckToken_Request)(nil),         // 17: outer.CheckToken.Request
	(*CheckToken_Reply)(nil),           // 18: outer.CheckToken.Reply
	(*UploadIcon_Request)(nil),         // 19: outer.UploadIcon.Request
	(*UploadIcon_Reply)(nil),           // 20: outer.UploadIcon.Reply
	(*GetGameTypes_Request)(nil),       // 21: outer.GetGameTypes.Request
	(*GetGameTypes_Reply)(nil),         // 22: outer.GetGameTypes.Reply
	(*DeleteAccount_Request)(nil),      // 23: outer.DeleteAccount.Request
	(*DeleteAccount_Reply)(nil),        // 24: outer.DeleteAccount.Reply
	(*CheckClientVersion_Request)(nil), // 25: outer.CheckClientVersion.Request
	(*CheckClientVersion_Version)(nil), // 26: outer.CheckClientVersion.Version
	(*CheckClientVersion_Reply)(nil),   // 27: outer.CheckClientVersion.Reply
	(*GetRobotInfo_RobotInfo)(nil),     // 28: outer.GetRobotInfo.RobotInfo
	(*GetRobotInfo_Request)(nil),       // 29: outer.GetRobotInfo.Request
	(*GetRobotInfo_Reply)(nil),         // 30: outer.GetRobotInfo.Reply
	(*UpdateRobotInfo_RobotInfo)(nil),  // 31: outer.UpdateRobotInfo.RobotInfo
	(*UpdateRobotInfo_Request)(nil),    // 32: outer.UpdateRobotInfo.Request
	(*UpdateRobotInfo_Reply)(nil),      // 33: outer.UpdateRobotInfo.Reply
}
var file_outer_web_proto_depIdxs = []int32{
	0,  // 0: outer.WebLoginUseInfo.UserInfo.state:type_name -> outer.WebLoginUseInfo.State
	14, // 1: outer.CheckCaptcha.Reply.userInfo:type_name -> outer.WebLoginUseInfo.UserInfo
	26, // 2: outer.CheckClientVersion.Reply.lastVersion:type_name -> outer.CheckClientVersion.Version
	28, // 3: outer.GetRobotInfo.Reply.robotInfo:type_name -> outer.GetRobotInfo.RobotInfo
	31, // 4: outer.UpdateRobotInfo.Request.robotInfo:type_name -> outer.UpdateRobotInfo.RobotInfo
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_outer_web_proto_init() }
func file_outer_web_proto_init() {
	if File_outer_web_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_outer_web_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCaptcha); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebLoginUseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckCaptcha); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadIcon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameTypes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckClientVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRobotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRobotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCaptcha_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCaptcha_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebLoginUseInfo_UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckCaptcha_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckCaptcha_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckToken_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckToken_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadIcon_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadIcon_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameTypes_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameTypes_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAccount_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAccount_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckClientVersion_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckClientVersion_Version); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckClientVersion_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRobotInfo_RobotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRobotInfo_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRobotInfo_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRobotInfo_RobotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRobotInfo_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outer_web_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRobotInfo_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_outer_web_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outer_web_proto_goTypes,
		DependencyIndexes: file_outer_web_proto_depIdxs,
		EnumInfos:         file_outer_web_proto_enumTypes,
		MessageInfos:      file_outer_web_proto_msgTypes,
	}.Build()
	File_outer_web_proto = out.File
	file_outer_web_proto_rawDesc = nil
	file_outer_web_proto_goTypes = nil
	file_outer_web_proto_depIdxs = nil
}
