// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.5.1
// source: inner/2group.proto

package inner

import (
	actor "github.com/asynkron/protoactor-go/actor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//用户上线
type Ho2GrPlayerOnline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrPlayerOnline) Reset() {
	*x = Ho2GrPlayerOnline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrPlayerOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrPlayerOnline) ProtoMessage() {}

func (x *Ho2GrPlayerOnline) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrPlayerOnline.ProtoReflect.Descriptor instead.
func (*Ho2GrPlayerOnline) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{0}
}

//用户离线
type Ho2GrPlayerOffline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrPlayerOffline) Reset() {
	*x = Ho2GrPlayerOffline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrPlayerOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrPlayerOffline) ProtoMessage() {}

func (x *Ho2GrPlayerOffline) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrPlayerOffline.ProtoReflect.Descriptor instead.
func (*Ho2GrPlayerOffline) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{1}
}

//用户在线的心跳
type Ho2GrPlayerHeartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrPlayerHeartbeat) Reset() {
	*x = Ho2GrPlayerHeartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrPlayerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrPlayerHeartbeat) ProtoMessage() {}

func (x *Ho2GrPlayerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrPlayerHeartbeat.ProtoReflect.Descriptor instead.
func (*Ho2GrPlayerHeartbeat) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{2}
}

//创建群
type Ho2GrCreateGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrCreateGroup) Reset() {
	*x = Ho2GrCreateGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrCreateGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrCreateGroup) ProtoMessage() {}

func (x *Ho2GrCreateGroup) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrCreateGroup.ProtoReflect.Descriptor instead.
func (*Ho2GrCreateGroup) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{3}
}

//加入群【注: 其实就是添加到收藏列表】
type Ho2GrFavoriteGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrFavoriteGroup) Reset() {
	*x = Ho2GrFavoriteGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrFavoriteGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrFavoriteGroup) ProtoMessage() {}

func (x *Ho2GrFavoriteGroup) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrFavoriteGroup.ProtoReflect.Descriptor instead.
func (*Ho2GrFavoriteGroup) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{4}
}

//退出群【注: 退出后不在群，离开只是当前不在】
type Ho2GrUnfavoriteGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrUnfavoriteGroup) Reset() {
	*x = Ho2GrUnfavoriteGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrUnfavoriteGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrUnfavoriteGroup) ProtoMessage() {}

func (x *Ho2GrUnfavoriteGroup) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrUnfavoriteGroup.ProtoReflect.Descriptor instead.
func (*Ho2GrUnfavoriteGroup) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{5}
}

//解散群
type Ho2GrDisbandGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrDisbandGroup) Reset() {
	*x = Ho2GrDisbandGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrDisbandGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrDisbandGroup) ProtoMessage() {}

func (x *Ho2GrDisbandGroup) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrDisbandGroup.ProtoReflect.Descriptor instead.
func (*Ho2GrDisbandGroup) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{6}
}

//进入群 【注: 进入表示当前在某个群。只有当前所在才能收到部分推送】
type Ho2GrEnterGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrEnterGroup) Reset() {
	*x = Ho2GrEnterGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrEnterGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrEnterGroup) ProtoMessage() {}

func (x *Ho2GrEnterGroup) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrEnterGroup.ProtoReflect.Descriptor instead.
func (*Ho2GrEnterGroup) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{7}
}

//离开群 【注: 退出后不在群，离开只是当前不在】
type Ho2GrExitGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrExitGroup) Reset() {
	*x = Ho2GrExitGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrExitGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrExitGroup) ProtoMessage() {}

func (x *Ho2GrExitGroup) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrExitGroup.ProtoReflect.Descriptor instead.
func (*Ho2GrExitGroup) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{8}
}

type Ho2GrPlayerOnline_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     uint64     `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Session *actor.PID `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"` //
}

func (x *Ho2GrPlayerOnline_Request) Reset() {
	*x = Ho2GrPlayerOnline_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrPlayerOnline_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrPlayerOnline_Request) ProtoMessage() {}

func (x *Ho2GrPlayerOnline_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrPlayerOnline_Request.ProtoReflect.Descriptor instead.
func (*Ho2GrPlayerOnline_Request) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Ho2GrPlayerOnline_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Ho2GrPlayerOnline_Request) GetSession() *actor.PID {
	if x != nil {
		return x.Session
	}
	return nil
}

type Ho2GrPlayerOnline_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastChatId uint64 `protobuf:"varint,1,opt,name=lastChatId,proto3" json:"lastChatId,omitempty"`
}

func (x *Ho2GrPlayerOnline_Reply) Reset() {
	*x = Ho2GrPlayerOnline_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrPlayerOnline_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrPlayerOnline_Reply) ProtoMessage() {}

func (x *Ho2GrPlayerOnline_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrPlayerOnline_Reply.ProtoReflect.Descriptor instead.
func (*Ho2GrPlayerOnline_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Ho2GrPlayerOnline_Reply) GetLastChatId() uint64 {
	if x != nil {
		return x.LastChatId
	}
	return 0
}

type Ho2GrPlayerOffline_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     uint64     `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Session *actor.PID `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *Ho2GrPlayerOffline_Request) Reset() {
	*x = Ho2GrPlayerOffline_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrPlayerOffline_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrPlayerOffline_Request) ProtoMessage() {}

func (x *Ho2GrPlayerOffline_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrPlayerOffline_Request.ProtoReflect.Descriptor instead.
func (*Ho2GrPlayerOffline_Request) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Ho2GrPlayerOffline_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Ho2GrPlayerOffline_Request) GetSession() *actor.PID {
	if x != nil {
		return x.Session
	}
	return nil
}

type Ho2GrPlayerOffline_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrPlayerOffline_Reply) Reset() {
	*x = Ho2GrPlayerOffline_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrPlayerOffline_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrPlayerOffline_Reply) ProtoMessage() {}

func (x *Ho2GrPlayerOffline_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrPlayerOffline_Reply.ProtoReflect.Descriptor instead.
func (*Ho2GrPlayerOffline_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{1, 1}
}

type Ho2GrPlayerHeartbeat_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Ho2GrPlayerHeartbeat_Request) Reset() {
	*x = Ho2GrPlayerHeartbeat_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrPlayerHeartbeat_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrPlayerHeartbeat_Request) ProtoMessage() {}

func (x *Ho2GrPlayerHeartbeat_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrPlayerHeartbeat_Request.ProtoReflect.Descriptor instead.
func (*Ho2GrPlayerHeartbeat_Request) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Ho2GrPlayerHeartbeat_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type Ho2GrPlayerHeartbeat_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrPlayerHeartbeat_Reply) Reset() {
	*x = Ho2GrPlayerHeartbeat_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrPlayerHeartbeat_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrPlayerHeartbeat_Reply) ProtoMessage() {}

func (x *Ho2GrPlayerHeartbeat_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrPlayerHeartbeat_Reply.ProtoReflect.Descriptor instead.
func (*Ho2GrPlayerHeartbeat_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{2, 1}
}

type Ho2GrCreateGroup_Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     uint64     `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Session *actor.PID `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"` //
}

func (x *Ho2GrCreateGroup_Player) Reset() {
	*x = Ho2GrCreateGroup_Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrCreateGroup_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrCreateGroup_Player) ProtoMessage() {}

func (x *Ho2GrCreateGroup_Player) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrCreateGroup_Player.ProtoReflect.Descriptor instead.
func (*Ho2GrCreateGroup_Player) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Ho2GrCreateGroup_Player) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Ho2GrCreateGroup_Player) GetSession() *actor.PID {
	if x != nil {
		return x.Session
	}
	return nil
}

type Ho2GrCreateGroup_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner     *Ho2GrCreateGroup_Player `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`         //创建者
	GroupName string                   `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"` //群名字
	GroupIcon string                   `protobuf:"bytes,3,opt,name=groupIcon,proto3" json:"groupIcon,omitempty"` //群icon
	GroupDes  string                   `protobuf:"bytes,4,opt,name=groupDes,proto3" json:"groupDes,omitempty"`   //群描述
	GameType  string                   `protobuf:"bytes,5,opt,name=gameType,proto3" json:"gameType,omitempty"`   //游戏类型
}

func (x *Ho2GrCreateGroup_Request) Reset() {
	*x = Ho2GrCreateGroup_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrCreateGroup_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrCreateGroup_Request) ProtoMessage() {}

func (x *Ho2GrCreateGroup_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrCreateGroup_Request.ProtoReflect.Descriptor instead.
func (*Ho2GrCreateGroup_Request) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Ho2GrCreateGroup_Request) GetOwner() *Ho2GrCreateGroup_Player {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Ho2GrCreateGroup_Request) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Ho2GrCreateGroup_Request) GetGroupIcon() string {
	if x != nil {
		return x.GroupIcon
	}
	return ""
}

func (x *Ho2GrCreateGroup_Request) GetGroupDes() string {
	if x != nil {
		return x.GroupDes
	}
	return ""
}

func (x *Ho2GrCreateGroup_Request) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

type Ho2GrCreateGroup_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrCreateGroup_Reply) Reset() {
	*x = Ho2GrCreateGroup_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrCreateGroup_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrCreateGroup_Reply) ProtoMessage() {}

func (x *Ho2GrCreateGroup_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrCreateGroup_Reply.ProtoReflect.Descriptor instead.
func (*Ho2GrCreateGroup_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{3, 2}
}

type Ho2GrFavoriteGroup_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Ho2GrFavoriteGroup_Request) Reset() {
	*x = Ho2GrFavoriteGroup_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrFavoriteGroup_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrFavoriteGroup_Request) ProtoMessage() {}

func (x *Ho2GrFavoriteGroup_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrFavoriteGroup_Request.ProtoReflect.Descriptor instead.
func (*Ho2GrFavoriteGroup_Request) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Ho2GrFavoriteGroup_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type Ho2GrFavoriteGroup_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransferOwner bool `protobuf:"varint,1,opt,name=transferOwner,proto3" json:"transferOwner,omitempty"` //是否转移拥有者~机器人创建的群转移给第一个进入的玩家
}

func (x *Ho2GrFavoriteGroup_Reply) Reset() {
	*x = Ho2GrFavoriteGroup_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrFavoriteGroup_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrFavoriteGroup_Reply) ProtoMessage() {}

func (x *Ho2GrFavoriteGroup_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrFavoriteGroup_Reply.ProtoReflect.Descriptor instead.
func (*Ho2GrFavoriteGroup_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Ho2GrFavoriteGroup_Reply) GetTransferOwner() bool {
	if x != nil {
		return x.TransferOwner
	}
	return false
}

type Ho2GrUnfavoriteGroup_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Ho2GrUnfavoriteGroup_Request) Reset() {
	*x = Ho2GrUnfavoriteGroup_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrUnfavoriteGroup_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrUnfavoriteGroup_Request) ProtoMessage() {}

func (x *Ho2GrUnfavoriteGroup_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrUnfavoriteGroup_Request.ProtoReflect.Descriptor instead.
func (*Ho2GrUnfavoriteGroup_Request) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Ho2GrUnfavoriteGroup_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type Ho2GrUnfavoriteGroup_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrUnfavoriteGroup_Reply) Reset() {
	*x = Ho2GrUnfavoriteGroup_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrUnfavoriteGroup_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrUnfavoriteGroup_Reply) ProtoMessage() {}

func (x *Ho2GrUnfavoriteGroup_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrUnfavoriteGroup_Reply.ProtoReflect.Descriptor instead.
func (*Ho2GrUnfavoriteGroup_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{5, 1}
}

type Ho2GrDisbandGroup_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Ho2GrDisbandGroup_Request) Reset() {
	*x = Ho2GrDisbandGroup_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrDisbandGroup_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrDisbandGroup_Request) ProtoMessage() {}

func (x *Ho2GrDisbandGroup_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrDisbandGroup_Request.ProtoReflect.Descriptor instead.
func (*Ho2GrDisbandGroup_Request) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Ho2GrDisbandGroup_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type Ho2GrDisbandGroup_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrDisbandGroup_Reply) Reset() {
	*x = Ho2GrDisbandGroup_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrDisbandGroup_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrDisbandGroup_Reply) ProtoMessage() {}

func (x *Ho2GrDisbandGroup_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrDisbandGroup_Reply.ProtoReflect.Descriptor instead.
func (*Ho2GrDisbandGroup_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{6, 1}
}

type Ho2GrEnterGroup_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *actor.PID `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Uid     uint64     `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Ho2GrEnterGroup_Request) Reset() {
	*x = Ho2GrEnterGroup_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrEnterGroup_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrEnterGroup_Request) ProtoMessage() {}

func (x *Ho2GrEnterGroup_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrEnterGroup_Request.ProtoReflect.Descriptor instead.
func (*Ho2GrEnterGroup_Request) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Ho2GrEnterGroup_Request) GetSession() *actor.PID {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *Ho2GrEnterGroup_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type Ho2GrEnterGroup_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrEnterGroup_Reply) Reset() {
	*x = Ho2GrEnterGroup_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrEnterGroup_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrEnterGroup_Reply) ProtoMessage() {}

func (x *Ho2GrEnterGroup_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrEnterGroup_Reply.ProtoReflect.Descriptor instead.
func (*Ho2GrEnterGroup_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{7, 1}
}

type Ho2GrExitGroup_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Ho2GrExitGroup_Request) Reset() {
	*x = Ho2GrExitGroup_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrExitGroup_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrExitGroup_Request) ProtoMessage() {}

func (x *Ho2GrExitGroup_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrExitGroup_Request.ProtoReflect.Descriptor instead.
func (*Ho2GrExitGroup_Request) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Ho2GrExitGroup_Request) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type Ho2GrExitGroup_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2GrExitGroup_Reply) Reset() {
	*x = Ho2GrExitGroup_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2group_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2GrExitGroup_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2GrExitGroup_Reply) ProtoMessage() {}

func (x *Ho2GrExitGroup_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2group_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2GrExitGroup_Reply.ProtoReflect.Descriptor instead.
func (*Ho2GrExitGroup_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2group_proto_rawDescGZIP(), []int{8, 1}
}

var File_inner_2group_proto protoreflect.FileDescriptor

var file_inner_2group_proto_rawDesc = []byte{
	0x0a, 0x12, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x32, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x1a, 0x11, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f,
	0x0a, 0x11, 0x48, 0x6f, 0x32, 0x47, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x1a, 0x41, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x24, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x07, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x27, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x1e, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x22,
	0x60, 0x0a, 0x12, 0x48, 0x6f, 0x32, 0x47, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4f, 0x66,
	0x66, 0x6c, 0x69, 0x6e, 0x65, 0x1a, 0x41, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x24, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52,
	0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x3c, 0x0a, 0x14, 0x48, 0x6f, 0x32, 0x47, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x1a, 0x1b, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x93, 0x02, 0x0a, 0x10, 0x48, 0x6f, 0x32, 0x47, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x1a, 0x40, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x24, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x07, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0xb3, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x48, 0x6f, 0x32, 0x47, 0x72, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x63, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x65, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x07, 0x0a, 0x05,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x60, 0x0a, 0x12, 0x48, 0x6f, 0x32, 0x47, 0x72, 0x46, 0x61,
	0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x1a, 0x1b, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x1a, 0x2d, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x3c, 0x0a, 0x14, 0x48, 0x6f, 0x32, 0x47, 0x72,
	0x55, 0x6e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x1a,
	0x1b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x1a, 0x07, 0x0a, 0x05,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x39, 0x0a, 0x11, 0x48, 0x6f, 0x32, 0x47, 0x72, 0x44, 0x69,
	0x73, 0x62, 0x61, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x1a, 0x1b, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x5d, 0x0a, 0x0f, 0x48, 0x6f, 0x32, 0x47, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x1a, 0x41, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24,
	0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x07, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x36, 0x0a, 0x0e, 0x48, 0x6f, 0x32, 0x47, 0x72, 0x45, 0x78, 0x69, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x1a, 0x1b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x1a, 0x07,
	0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x13, 0x5a, 0x11, 0x6c, 0x61, 0x69, 0x79, 0x61,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inner_2group_proto_rawDescOnce sync.Once
	file_inner_2group_proto_rawDescData = file_inner_2group_proto_rawDesc
)

func file_inner_2group_proto_rawDescGZIP() []byte {
	file_inner_2group_proto_rawDescOnce.Do(func() {
		file_inner_2group_proto_rawDescData = protoimpl.X.CompressGZIP(file_inner_2group_proto_rawDescData)
	})
	return file_inner_2group_proto_rawDescData
}

var file_inner_2group_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_inner_2group_proto_goTypes = []interface{}{
	(*Ho2GrPlayerOnline)(nil),            // 0: inner.Ho2GrPlayerOnline
	(*Ho2GrPlayerOffline)(nil),           // 1: inner.Ho2GrPlayerOffline
	(*Ho2GrPlayerHeartbeat)(nil),         // 2: inner.Ho2GrPlayerHeartbeat
	(*Ho2GrCreateGroup)(nil),             // 3: inner.Ho2GrCreateGroup
	(*Ho2GrFavoriteGroup)(nil),           // 4: inner.Ho2GrFavoriteGroup
	(*Ho2GrUnfavoriteGroup)(nil),         // 5: inner.Ho2GrUnfavoriteGroup
	(*Ho2GrDisbandGroup)(nil),            // 6: inner.Ho2GrDisbandGroup
	(*Ho2GrEnterGroup)(nil),              // 7: inner.Ho2GrEnterGroup
	(*Ho2GrExitGroup)(nil),               // 8: inner.Ho2GrExitGroup
	(*Ho2GrPlayerOnline_Request)(nil),    // 9: inner.Ho2GrPlayerOnline.Request
	(*Ho2GrPlayerOnline_Reply)(nil),      // 10: inner.Ho2GrPlayerOnline.Reply
	(*Ho2GrPlayerOffline_Request)(nil),   // 11: inner.Ho2GrPlayerOffline.Request
	(*Ho2GrPlayerOffline_Reply)(nil),     // 12: inner.Ho2GrPlayerOffline.Reply
	(*Ho2GrPlayerHeartbeat_Request)(nil), // 13: inner.Ho2GrPlayerHeartbeat.Request
	(*Ho2GrPlayerHeartbeat_Reply)(nil),   // 14: inner.Ho2GrPlayerHeartbeat.Reply
	(*Ho2GrCreateGroup_Player)(nil),      // 15: inner.Ho2GrCreateGroup.Player
	(*Ho2GrCreateGroup_Request)(nil),     // 16: inner.Ho2GrCreateGroup.Request
	(*Ho2GrCreateGroup_Reply)(nil),       // 17: inner.Ho2GrCreateGroup.Reply
	(*Ho2GrFavoriteGroup_Request)(nil),   // 18: inner.Ho2GrFavoriteGroup.Request
	(*Ho2GrFavoriteGroup_Reply)(nil),     // 19: inner.Ho2GrFavoriteGroup.Reply
	(*Ho2GrUnfavoriteGroup_Request)(nil), // 20: inner.Ho2GrUnfavoriteGroup.Request
	(*Ho2GrUnfavoriteGroup_Reply)(nil),   // 21: inner.Ho2GrUnfavoriteGroup.Reply
	(*Ho2GrDisbandGroup_Request)(nil),    // 22: inner.Ho2GrDisbandGroup.Request
	(*Ho2GrDisbandGroup_Reply)(nil),      // 23: inner.Ho2GrDisbandGroup.Reply
	(*Ho2GrEnterGroup_Request)(nil),      // 24: inner.Ho2GrEnterGroup.Request
	(*Ho2GrEnterGroup_Reply)(nil),        // 25: inner.Ho2GrEnterGroup.Reply
	(*Ho2GrExitGroup_Request)(nil),       // 26: inner.Ho2GrExitGroup.Request
	(*Ho2GrExitGroup_Reply)(nil),         // 27: inner.Ho2GrExitGroup.Reply
	(*actor.PID)(nil),                    // 28: actor.PID
}
var file_inner_2group_proto_depIdxs = []int32{
	28, // 0: inner.Ho2GrPlayerOnline.Request.session:type_name -> actor.PID
	28, // 1: inner.Ho2GrPlayerOffline.Request.session:type_name -> actor.PID
	28, // 2: inner.Ho2GrCreateGroup.Player.session:type_name -> actor.PID
	15, // 3: inner.Ho2GrCreateGroup.Request.owner:type_name -> inner.Ho2GrCreateGroup.Player
	28, // 4: inner.Ho2GrEnterGroup.Request.session:type_name -> actor.PID
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_inner_2group_proto_init() }
func file_inner_2group_proto_init() {
	if File_inner_2group_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inner_2group_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrPlayerOnline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrPlayerOffline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrPlayerHeartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrCreateGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrFavoriteGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrUnfavoriteGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrDisbandGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrEnterGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrExitGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrPlayerOnline_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrPlayerOnline_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrPlayerOffline_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrPlayerOffline_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrPlayerHeartbeat_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrPlayerHeartbeat_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrCreateGroup_Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrCreateGroup_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrCreateGroup_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrFavoriteGroup_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrFavoriteGroup_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrUnfavoriteGroup_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrUnfavoriteGroup_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrDisbandGroup_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrDisbandGroup_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrEnterGroup_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrEnterGroup_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrExitGroup_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2group_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2GrExitGroup_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inner_2group_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inner_2group_proto_goTypes,
		DependencyIndexes: file_inner_2group_proto_depIdxs,
		MessageInfos:      file_inner_2group_proto_msgTypes,
	}.Build()
	File_inner_2group_proto = out.File
	file_inner_2group_proto_rawDesc = nil
	file_inner_2group_proto_goTypes = nil
	file_inner_2group_proto_depIdxs = nil
}
