// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.5.1
// source: inner/2hall.proto

package inner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//更新群信息
type Gr2HaUpdateGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Gr2HaUpdateGroup) Reset() {
	*x = Gr2HaUpdateGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2hall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2HaUpdateGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2HaUpdateGroup) ProtoMessage() {}

func (x *Gr2HaUpdateGroup) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2hall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2HaUpdateGroup.ProtoReflect.Descriptor instead.
func (*Gr2HaUpdateGroup) Descriptor() ([]byte, []int) {
	return file_inner_2hall_proto_rawDescGZIP(), []int{0}
}

//删除群
type Gr2HaDeleteGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Gr2HaDeleteGroup) Reset() {
	*x = Gr2HaDeleteGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2hall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2HaDeleteGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2HaDeleteGroup) ProtoMessage() {}

func (x *Gr2HaDeleteGroup) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2hall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2HaDeleteGroup.ProtoReflect.Descriptor instead.
func (*Gr2HaDeleteGroup) Descriptor() ([]byte, []int) {
	return file_inner_2hall_proto_rawDescGZIP(), []int{1}
}

//查找合适的群--可进入的
type We2HaLookingGroupAvailable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *We2HaLookingGroupAvailable) Reset() {
	*x = We2HaLookingGroupAvailable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2hall_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *We2HaLookingGroupAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*We2HaLookingGroupAvailable) ProtoMessage() {}

func (x *We2HaLookingGroupAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2hall_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use We2HaLookingGroupAvailable.ProtoReflect.Descriptor instead.
func (*We2HaLookingGroupAvailable) Descriptor() ([]byte, []int) {
	return file_inner_2hall_proto_rawDescGZIP(), []int{2}
}

//用户上线
type Ho2HaCheckInviteBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ho2HaCheckInviteBroadcast) Reset() {
	*x = Ho2HaCheckInviteBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2hall_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2HaCheckInviteBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2HaCheckInviteBroadcast) ProtoMessage() {}

func (x *Ho2HaCheckInviteBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2hall_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2HaCheckInviteBroadcast.ProtoReflect.Descriptor instead.
func (*Ho2HaCheckInviteBroadcast) Descriptor() ([]byte, []int) {
	return file_inner_2hall_proto_rawDescGZIP(), []int{3}
}

type Gr2HaUpdateGroup_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid                  uint64 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Name                 string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VoiceRoomName        string `protobuf:"bytes,3,opt,name=voiceRoomName,proto3" json:"voiceRoomName,omitempty"`
	GameType             string `protobuf:"bytes,4,opt,name=gameType,proto3" json:"gameType,omitempty"`
	SortScore            uint64 `protobuf:"varint,5,opt,name=sortScore,proto3" json:"sortScore,omitempty"`
	TempVoiceRoomVersion uint64 `protobuf:"varint,6,opt,name=tempVoiceRoomVersion,proto3" json:"tempVoiceRoomVersion,omitempty"` //临时的语音房间版本,用于过滤重复的摇人--垃圾需求的临时实现
}

func (x *Gr2HaUpdateGroup_Request) Reset() {
	*x = Gr2HaUpdateGroup_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2hall_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2HaUpdateGroup_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2HaUpdateGroup_Request) ProtoMessage() {}

func (x *Gr2HaUpdateGroup_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2hall_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2HaUpdateGroup_Request.ProtoReflect.Descriptor instead.
func (*Gr2HaUpdateGroup_Request) Descriptor() ([]byte, []int) {
	return file_inner_2hall_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Gr2HaUpdateGroup_Request) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Gr2HaUpdateGroup_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Gr2HaUpdateGroup_Request) GetVoiceRoomName() string {
	if x != nil {
		return x.VoiceRoomName
	}
	return ""
}

func (x *Gr2HaUpdateGroup_Request) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *Gr2HaUpdateGroup_Request) GetSortScore() uint64 {
	if x != nil {
		return x.SortScore
	}
	return 0
}

func (x *Gr2HaUpdateGroup_Request) GetTempVoiceRoomVersion() uint64 {
	if x != nil {
		return x.TempVoiceRoomVersion
	}
	return 0
}

type Gr2HaUpdateGroup_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Gr2HaUpdateGroup_Reply) Reset() {
	*x = Gr2HaUpdateGroup_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2hall_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2HaUpdateGroup_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2HaUpdateGroup_Reply) ProtoMessage() {}

func (x *Gr2HaUpdateGroup_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2hall_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2HaUpdateGroup_Reply.ProtoReflect.Descriptor instead.
func (*Gr2HaUpdateGroup_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2hall_proto_rawDescGZIP(), []int{0, 1}
}

type Gr2HaDeleteGroup_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid uint64 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
}

func (x *Gr2HaDeleteGroup_Request) Reset() {
	*x = Gr2HaDeleteGroup_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2hall_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2HaDeleteGroup_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2HaDeleteGroup_Request) ProtoMessage() {}

func (x *Gr2HaDeleteGroup_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2hall_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2HaDeleteGroup_Request.ProtoReflect.Descriptor instead.
func (*Gr2HaDeleteGroup_Request) Descriptor() ([]byte, []int) {
	return file_inner_2hall_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Gr2HaDeleteGroup_Request) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type Gr2HaDeleteGroup_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Gr2HaDeleteGroup_Reply) Reset() {
	*x = Gr2HaDeleteGroup_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2hall_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2HaDeleteGroup_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2HaDeleteGroup_Reply) ProtoMessage() {}

func (x *Gr2HaDeleteGroup_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2hall_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2HaDeleteGroup_Reply.ProtoReflect.Descriptor instead.
func (*Gr2HaDeleteGroup_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2hall_proto_rawDescGZIP(), []int{1, 1}
}

type We2HaLookingGroupAvailable_Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid              uint64 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	GroupName        string `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	VoiceRoomName    string `protobuf:"bytes,3,opt,name=voiceRoomName,proto3" json:"voiceRoomName,omitempty"`
	OnMicPlayerCount int32  `protobuf:"varint,4,opt,name=onMicPlayerCount,proto3" json:"onMicPlayerCount,omitempty"`
}

func (x *We2HaLookingGroupAvailable_Group) Reset() {
	*x = We2HaLookingGroupAvailable_Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2hall_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *We2HaLookingGroupAvailable_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*We2HaLookingGroupAvailable_Group) ProtoMessage() {}

func (x *We2HaLookingGroupAvailable_Group) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2hall_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use We2HaLookingGroupAvailable_Group.ProtoReflect.Descriptor instead.
func (*We2HaLookingGroupAvailable_Group) Descriptor() ([]byte, []int) {
	return file_inner_2hall_proto_rawDescGZIP(), []int{2, 0}
}

func (x *We2HaLookingGroupAvailable_Group) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *We2HaLookingGroupAvailable_Group) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *We2HaLookingGroupAvailable_Group) GetVoiceRoomName() string {
	if x != nil {
		return x.VoiceRoomName
	}
	return ""
}

func (x *We2HaLookingGroupAvailable_Group) GetOnMicPlayerCount() int32 {
	if x != nil {
		return x.OnMicPlayerCount
	}
	return 0
}

type We2HaLookingGroupAvailable_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameType string `protobuf:"bytes,1,opt,name=gameType,proto3" json:"gameType,omitempty"` //游戏类型
}

func (x *We2HaLookingGroupAvailable_Request) Reset() {
	*x = We2HaLookingGroupAvailable_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2hall_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *We2HaLookingGroupAvailable_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*We2HaLookingGroupAvailable_Request) ProtoMessage() {}

func (x *We2HaLookingGroupAvailable_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2hall_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use We2HaLookingGroupAvailable_Request.ProtoReflect.Descriptor instead.
func (*We2HaLookingGroupAvailable_Request) Descriptor() ([]byte, []int) {
	return file_inner_2hall_proto_rawDescGZIP(), []int{2, 1}
}

func (x *We2HaLookingGroupAvailable_Request) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

type We2HaLookingGroupAvailable_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []*We2HaLookingGroupAvailable_Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *We2HaLookingGroupAvailable_Reply) Reset() {
	*x = We2HaLookingGroupAvailable_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2hall_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *We2HaLookingGroupAvailable_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*We2HaLookingGroupAvailable_Reply) ProtoMessage() {}

func (x *We2HaLookingGroupAvailable_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2hall_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use We2HaLookingGroupAvailable_Reply.ProtoReflect.Descriptor instead.
func (*We2HaLookingGroupAvailable_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2hall_proto_rawDescGZIP(), []int{2, 2}
}

func (x *We2HaLookingGroupAvailable_Reply) GetGroups() []*We2HaLookingGroupAvailable_Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type Ho2HaCheckInviteBroadcast_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameType string `protobuf:"bytes,1,opt,name=gameType,proto3" json:"gameType,omitempty"` //游戏类型
}

func (x *Ho2HaCheckInviteBroadcast_Request) Reset() {
	*x = Ho2HaCheckInviteBroadcast_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2hall_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2HaCheckInviteBroadcast_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2HaCheckInviteBroadcast_Request) ProtoMessage() {}

func (x *Ho2HaCheckInviteBroadcast_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2hall_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2HaCheckInviteBroadcast_Request.ProtoReflect.Descriptor instead.
func (*Ho2HaCheckInviteBroadcast_Request) Descriptor() ([]byte, []int) {
	return file_inner_2hall_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Ho2HaCheckInviteBroadcast_Request) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

type Ho2HaCheckInviteBroadcast_MatchGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid                  uint64 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`                                   //群id
	PlayerCount          uint32 `protobuf:"varint,2,opt,name=playerCount,proto3" json:"playerCount,omitempty"`                   //人数
	TempVoiceRoomVersion uint64 `protobuf:"varint,3,opt,name=tempVoiceRoomVersion,proto3" json:"tempVoiceRoomVersion,omitempty"` //临时的语音房间版本,用于过滤重复的摇人--垃圾需求的临时实现
}

func (x *Ho2HaCheckInviteBroadcast_MatchGroup) Reset() {
	*x = Ho2HaCheckInviteBroadcast_MatchGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2hall_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2HaCheckInviteBroadcast_MatchGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2HaCheckInviteBroadcast_MatchGroup) ProtoMessage() {}

func (x *Ho2HaCheckInviteBroadcast_MatchGroup) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2hall_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2HaCheckInviteBroadcast_MatchGroup.ProtoReflect.Descriptor instead.
func (*Ho2HaCheckInviteBroadcast_MatchGroup) Descriptor() ([]byte, []int) {
	return file_inner_2hall_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Ho2HaCheckInviteBroadcast_MatchGroup) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Ho2HaCheckInviteBroadcast_MatchGroup) GetPlayerCount() uint32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *Ho2HaCheckInviteBroadcast_MatchGroup) GetTempVoiceRoomVersion() uint64 {
	if x != nil {
		return x.TempVoiceRoomVersion
	}
	return 0
}

type Ho2HaCheckInviteBroadcast_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchGroups []*Ho2HaCheckInviteBroadcast_MatchGroup `protobuf:"bytes,1,rep,name=matchGroups,proto3" json:"matchGroups,omitempty"`
}

func (x *Ho2HaCheckInviteBroadcast_Reply) Reset() {
	*x = Ho2HaCheckInviteBroadcast_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2hall_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ho2HaCheckInviteBroadcast_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ho2HaCheckInviteBroadcast_Reply) ProtoMessage() {}

func (x *Ho2HaCheckInviteBroadcast_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2hall_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ho2HaCheckInviteBroadcast_Reply.ProtoReflect.Descriptor instead.
func (*Ho2HaCheckInviteBroadcast_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2hall_proto_rawDescGZIP(), []int{3, 2}
}

func (x *Ho2HaCheckInviteBroadcast_Reply) GetMatchGroups() []*Ho2HaCheckInviteBroadcast_MatchGroup {
	if x != nil {
		return x.MatchGroups
	}
	return nil
}

var File_inner_2hall_proto protoreflect.FileDescriptor

var file_inner_2hall_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x32, 0x68, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0xe1, 0x01, 0x0a, 0x10, 0x47,
	0x72, 0x32, 0x48, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x1a,
	0xc3, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x67,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x32, 0x0a, 0x14, 0x74, 0x65, 0x6d, 0x70, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x14, 0x74, 0x65, 0x6d, 0x70, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x38,
	0x0a, 0x10, 0x47, 0x72, 0x32, 0x48, 0x61, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x1a, 0x1b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x1a,
	0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x99, 0x02, 0x0a, 0x1a, 0x57, 0x65, 0x32,
	0x48, 0x61, 0x4c, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x89, 0x01, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x67, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x6f, 0x6e, 0x4d, 0x69, 0x63,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x10, 0x6f, 0x6e, 0x4d, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x1a, 0x25, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x48, 0x0a, 0x05, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x3f, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x57, 0x65, 0x32, 0x48,
	0x61, 0x4c, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x06, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x22, 0x90, 0x02, 0x0a, 0x19, 0x48, 0x6f, 0x32, 0x48, 0x61, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x1a, 0x25, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x74, 0x0a, 0x0a, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x14, 0x74,
	0x65, 0x6d, 0x70, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x14, 0x74, 0x65, 0x6d, 0x70, 0x56,
	0x6f, 0x69, 0x63, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a,
	0x56, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x48, 0x6f, 0x32, 0x48, 0x61, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2e,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0b, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x42, 0x13, 0x5a, 0x11, 0x6c, 0x61, 0x69, 0x79, 0x61,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inner_2hall_proto_rawDescOnce sync.Once
	file_inner_2hall_proto_rawDescData = file_inner_2hall_proto_rawDesc
)

func file_inner_2hall_proto_rawDescGZIP() []byte {
	file_inner_2hall_proto_rawDescOnce.Do(func() {
		file_inner_2hall_proto_rawDescData = protoimpl.X.CompressGZIP(file_inner_2hall_proto_rawDescData)
	})
	return file_inner_2hall_proto_rawDescData
}

var file_inner_2hall_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_inner_2hall_proto_goTypes = []interface{}{
	(*Gr2HaUpdateGroup)(nil),                     // 0: inner.Gr2HaUpdateGroup
	(*Gr2HaDeleteGroup)(nil),                     // 1: inner.Gr2HaDeleteGroup
	(*We2HaLookingGroupAvailable)(nil),           // 2: inner.We2HaLookingGroupAvailable
	(*Ho2HaCheckInviteBroadcast)(nil),            // 3: inner.Ho2HaCheckInviteBroadcast
	(*Gr2HaUpdateGroup_Request)(nil),             // 4: inner.Gr2HaUpdateGroup.Request
	(*Gr2HaUpdateGroup_Reply)(nil),               // 5: inner.Gr2HaUpdateGroup.Reply
	(*Gr2HaDeleteGroup_Request)(nil),             // 6: inner.Gr2HaDeleteGroup.Request
	(*Gr2HaDeleteGroup_Reply)(nil),               // 7: inner.Gr2HaDeleteGroup.Reply
	(*We2HaLookingGroupAvailable_Group)(nil),     // 8: inner.We2HaLookingGroupAvailable.Group
	(*We2HaLookingGroupAvailable_Request)(nil),   // 9: inner.We2HaLookingGroupAvailable.Request
	(*We2HaLookingGroupAvailable_Reply)(nil),     // 10: inner.We2HaLookingGroupAvailable.Reply
	(*Ho2HaCheckInviteBroadcast_Request)(nil),    // 11: inner.Ho2HaCheckInviteBroadcast.Request
	(*Ho2HaCheckInviteBroadcast_MatchGroup)(nil), // 12: inner.Ho2HaCheckInviteBroadcast.MatchGroup
	(*Ho2HaCheckInviteBroadcast_Reply)(nil),      // 13: inner.Ho2HaCheckInviteBroadcast.Reply
}
var file_inner_2hall_proto_depIdxs = []int32{
	8,  // 0: inner.We2HaLookingGroupAvailable.Reply.groups:type_name -> inner.We2HaLookingGroupAvailable.Group
	12, // 1: inner.Ho2HaCheckInviteBroadcast.Reply.matchGroups:type_name -> inner.Ho2HaCheckInviteBroadcast.MatchGroup
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_inner_2hall_proto_init() }
func file_inner_2hall_proto_init() {
	if File_inner_2hall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inner_2hall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2HaUpdateGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2hall_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2HaDeleteGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2hall_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*We2HaLookingGroupAvailable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2hall_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2HaCheckInviteBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2hall_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2HaUpdateGroup_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2hall_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2HaUpdateGroup_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2hall_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2HaDeleteGroup_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2hall_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2HaDeleteGroup_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2hall_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*We2HaLookingGroupAvailable_Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2hall_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*We2HaLookingGroupAvailable_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2hall_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*We2HaLookingGroupAvailable_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2hall_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2HaCheckInviteBroadcast_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2hall_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2HaCheckInviteBroadcast_MatchGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2hall_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ho2HaCheckInviteBroadcast_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inner_2hall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inner_2hall_proto_goTypes,
		DependencyIndexes: file_inner_2hall_proto_depIdxs,
		MessageInfos:      file_inner_2hall_proto_msgTypes,
	}.Build()
	File_inner_2hall_proto = out.File
	file_inner_2hall_proto_rawDesc = nil
	file_inner_2hall_proto_goTypes = nil
	file_inner_2hall_proto_depIdxs = nil
}
