// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.5.1
// source: inner/2home.proto

package inner

import (
	actor "github.com/asynkron/protoactor-go/actor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "laiya/proto/common"
	outer "laiya/proto/outer"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//session建立
type C2HoSessionOnline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2HoSessionOnline) Reset() {
	*x = C2HoSessionOnline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2HoSessionOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2HoSessionOnline) ProtoMessage() {}

func (x *C2HoSessionOnline) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2HoSessionOnline.ProtoReflect.Descriptor instead.
func (*C2HoSessionOnline) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{0}
}

//session断开
type C2HoSessionOffline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2HoSessionOffline) Reset() {
	*x = C2HoSessionOffline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2HoSessionOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2HoSessionOffline) ProtoMessage() {}

func (x *C2HoSessionOffline) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2HoSessionOffline.ProtoReflect.Descriptor instead.
func (*C2HoSessionOffline) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{1}
}

//session心跳
type C2HoSessionHeartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2HoSessionHeartbeat) Reset() {
	*x = C2HoSessionHeartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2HoSessionHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2HoSessionHeartbeat) ProtoMessage() {}

func (x *C2HoSessionHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2HoSessionHeartbeat.ProtoReflect.Descriptor instead.
func (*C2HoSessionHeartbeat) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{2}
}

//删除用户
type Web2HoDeletePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Web2HoDeletePlayer) Reset() {
	*x = Web2HoDeletePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Web2HoDeletePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Web2HoDeletePlayer) ProtoMessage() {}

func (x *Web2HoDeletePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Web2HoDeletePlayer.ProtoReflect.Descriptor instead.
func (*Web2HoDeletePlayer) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{3}
}

//群解散了
type Gr2HoGroupDisband struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Gr2HoGroupDisband) Reset() {
	*x = Gr2HoGroupDisband{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2HoGroupDisband) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2HoGroupDisband) ProtoMessage() {}

func (x *Gr2HoGroupDisband) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2HoGroupDisband.ProtoReflect.Descriptor instead.
func (*Gr2HoGroupDisband) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{4}
}

//订阅群激活
type GroupActiveEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupActiveEvent) Reset() {
	*x = GroupActiveEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupActiveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupActiveEvent) ProtoMessage() {}

func (x *GroupActiveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupActiveEvent.ProtoReflect.Descriptor instead.
func (*GroupActiveEvent) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{5}
}

//发送私聊
type SendPrivateChatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendPrivateChatMsg) Reset() {
	*x = SendPrivateChatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPrivateChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateChatMsg) ProtoMessage() {}

func (x *SendPrivateChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateChatMsg.ProtoReflect.Descriptor instead.
func (*SendPrivateChatMsg) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{6}
}

type C2HoSessionOnline_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session           *actor.PID               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	LoginPlatformType common.LoginPlatformType `protobuf:"varint,2,opt,name=loginPlatformType,proto3,enum=common.LoginPlatformType" json:"loginPlatformType,omitempty"`
}

func (x *C2HoSessionOnline_Request) Reset() {
	*x = C2HoSessionOnline_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2HoSessionOnline_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2HoSessionOnline_Request) ProtoMessage() {}

func (x *C2HoSessionOnline_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2HoSessionOnline_Request.ProtoReflect.Descriptor instead.
func (*C2HoSessionOnline_Request) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{0, 0}
}

func (x *C2HoSessionOnline_Request) GetSession() *actor.PID {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *C2HoSessionOnline_Request) GetLoginPlatformType() common.LoginPlatformType {
	if x != nil {
		return x.LoginPlatformType
	}
	return common.LoginPlatformType(0)
}

type C2HoSessionOnline_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2HoSessionOnline_Reply) Reset() {
	*x = C2HoSessionOnline_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2HoSessionOnline_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2HoSessionOnline_Reply) ProtoMessage() {}

func (x *C2HoSessionOnline_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2HoSessionOnline_Reply.ProtoReflect.Descriptor instead.
func (*C2HoSessionOnline_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{0, 1}
}

type C2HoSessionOffline_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session           *actor.PID               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	LoginPlatformType common.LoginPlatformType `protobuf:"varint,2,opt,name=loginPlatformType,proto3,enum=common.LoginPlatformType" json:"loginPlatformType,omitempty"`
}

func (x *C2HoSessionOffline_Request) Reset() {
	*x = C2HoSessionOffline_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2HoSessionOffline_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2HoSessionOffline_Request) ProtoMessage() {}

func (x *C2HoSessionOffline_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2HoSessionOffline_Request.ProtoReflect.Descriptor instead.
func (*C2HoSessionOffline_Request) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{1, 0}
}

func (x *C2HoSessionOffline_Request) GetSession() *actor.PID {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *C2HoSessionOffline_Request) GetLoginPlatformType() common.LoginPlatformType {
	if x != nil {
		return x.LoginPlatformType
	}
	return common.LoginPlatformType(0)
}

type C2HoSessionOffline_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2HoSessionOffline_Reply) Reset() {
	*x = C2HoSessionOffline_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2HoSessionOffline_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2HoSessionOffline_Reply) ProtoMessage() {}

func (x *C2HoSessionOffline_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2HoSessionOffline_Reply.ProtoReflect.Descriptor instead.
func (*C2HoSessionOffline_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{1, 1}
}

type C2HoSessionHeartbeat_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session           *actor.PID               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	LoginPlatformType common.LoginPlatformType `protobuf:"varint,2,opt,name=loginPlatformType,proto3,enum=common.LoginPlatformType" json:"loginPlatformType,omitempty"`
}

func (x *C2HoSessionHeartbeat_Request) Reset() {
	*x = C2HoSessionHeartbeat_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2HoSessionHeartbeat_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2HoSessionHeartbeat_Request) ProtoMessage() {}

func (x *C2HoSessionHeartbeat_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2HoSessionHeartbeat_Request.ProtoReflect.Descriptor instead.
func (*C2HoSessionHeartbeat_Request) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{2, 0}
}

func (x *C2HoSessionHeartbeat_Request) GetSession() *actor.PID {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *C2HoSessionHeartbeat_Request) GetLoginPlatformType() common.LoginPlatformType {
	if x != nil {
		return x.LoginPlatformType
	}
	return common.LoginPlatformType(0)
}

type C2HoSessionHeartbeat_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2HoSessionHeartbeat_Reply) Reset() {
	*x = C2HoSessionHeartbeat_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2HoSessionHeartbeat_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2HoSessionHeartbeat_Reply) ProtoMessage() {}

func (x *C2HoSessionHeartbeat_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2HoSessionHeartbeat_Reply.ProtoReflect.Descriptor instead.
func (*C2HoSessionHeartbeat_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{2, 1}
}

type Web2HoDeletePlayer_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Web2HoDeletePlayer_Request) Reset() {
	*x = Web2HoDeletePlayer_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Web2HoDeletePlayer_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Web2HoDeletePlayer_Request) ProtoMessage() {}

func (x *Web2HoDeletePlayer_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Web2HoDeletePlayer_Request.ProtoReflect.Descriptor instead.
func (*Web2HoDeletePlayer_Request) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{3, 0}
}

type Web2HoDeletePlayer_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *Web2HoDeletePlayer_Reply) Reset() {
	*x = Web2HoDeletePlayer_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Web2HoDeletePlayer_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Web2HoDeletePlayer_Reply) ProtoMessage() {}

func (x *Web2HoDeletePlayer_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Web2HoDeletePlayer_Reply.ProtoReflect.Descriptor instead.
func (*Web2HoDeletePlayer_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Web2HoDeletePlayer_Reply) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type Gr2HoGroupDisband_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid uint64 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
}

func (x *Gr2HoGroupDisband_Request) Reset() {
	*x = Gr2HoGroupDisband_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2HoGroupDisband_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2HoGroupDisband_Request) ProtoMessage() {}

func (x *Gr2HoGroupDisband_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2HoGroupDisband_Request.ProtoReflect.Descriptor instead.
func (*Gr2HoGroupDisband_Request) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Gr2HoGroupDisband_Request) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type Gr2HoGroupDisband_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Gr2HoGroupDisband_Reply) Reset() {
	*x = Gr2HoGroupDisband_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2HoGroupDisband_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2HoGroupDisband_Reply) ProtoMessage() {}

func (x *Gr2HoGroupDisband_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2HoGroupDisband_Reply.ProtoReflect.Descriptor instead.
func (*Gr2HoGroupDisband_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{4, 1}
}

type GroupActiveEvent_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid uint64 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
}

func (x *GroupActiveEvent_Notify) Reset() {
	*x = GroupActiveEvent_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupActiveEvent_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupActiveEvent_Notify) ProtoMessage() {}

func (x *GroupActiveEvent_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupActiveEvent_Notify.ProtoReflect.Descriptor instead.
func (*GroupActiveEvent_Notify) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GroupActiveEvent_Notify) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type SendPrivateChatMsg_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderUid  uint64 `protobuf:"varint,1,opt,name=senderUid,proto3" json:"senderUid,omitempty"`  //发送者
	SenderName string `protobuf:"bytes,2,opt,name=senderName,proto3" json:"senderName,omitempty"` //发送者名字
	Uuid       uint64 `protobuf:"varint,3,opt,name=uuid,proto3" json:"uuid,omitempty"`            //
	Content    string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`       //文本内容[生效条件-MsgType.Normal|MsgType.UnknownMsgType]
	Url        string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`               //图片地址[生效条件-MsgType.Pic]
	//内容类型放最后
	MsgType outer.ChatMsg_MsgType `protobuf:"varint,100,opt,name=msgType,proto3,enum=outer.ChatMsg_MsgType" json:"msgType,omitempty"` //消息类型~
}

func (x *SendPrivateChatMsg_Request) Reset() {
	*x = SendPrivateChatMsg_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPrivateChatMsg_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateChatMsg_Request) ProtoMessage() {}

func (x *SendPrivateChatMsg_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateChatMsg_Request.ProtoReflect.Descriptor instead.
func (*SendPrivateChatMsg_Request) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{6, 0}
}

func (x *SendPrivateChatMsg_Request) GetSenderUid() uint64 {
	if x != nil {
		return x.SenderUid
	}
	return 0
}

func (x *SendPrivateChatMsg_Request) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *SendPrivateChatMsg_Request) GetUuid() uint64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *SendPrivateChatMsg_Request) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendPrivateChatMsg_Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SendPrivateChatMsg_Request) GetMsgType() outer.ChatMsg_MsgType {
	if x != nil {
		return x.MsgType
	}
	return outer.ChatMsg_MsgType(0)
}

type SendPrivateChatMsg_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendPrivateChatMsg_Reply) Reset() {
	*x = SendPrivateChatMsg_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2home_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPrivateChatMsg_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateChatMsg_Reply) ProtoMessage() {}

func (x *SendPrivateChatMsg_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2home_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateChatMsg_Reply.ProtoReflect.Descriptor instead.
func (*SendPrivateChatMsg_Reply) Descriptor() ([]byte, []int) {
	return file_inner_2home_proto_rawDescGZIP(), []int{6, 1}
}

var File_inner_2home_proto protoreflect.FileDescriptor

var file_inner_2home_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x32, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x1a, 0x11, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x18, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x01, 0x0a,
	0x11, 0x43, 0x32, 0x48, 0x6f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x1a, 0x78, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x11, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x11, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x07, 0x0a, 0x05,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x97, 0x01, 0x0a, 0x12, 0x43, 0x32, 0x48, 0x6f, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x1a, 0x78, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x50, 0x49, 0x44, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a,
	0x11, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x11, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x99, 0x01, 0x0a, 0x14, 0x43, 0x32, 0x48, 0x6f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x1a, 0x78, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44,
	0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x11, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x11, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x42, 0x0a, 0x12, 0x57,
	0x65, 0x62, 0x32, 0x48, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x0a, 0x05,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x39, 0x0a, 0x11, 0x47, 0x72, 0x32, 0x48, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x69, 0x73,
	0x62, 0x61, 0x6e, 0x64, 0x1a, 0x1b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69,
	0x64, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2e, 0x0a, 0x10, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x1a,
	0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x22, 0xd9, 0x01, 0x0a, 0x12, 0x53,
	0x65, 0x6e, 0x64, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73,
	0x67, 0x1a, 0xb9, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x55, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x30, 0x0a, 0x07, 0x6d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x4d, 0x73, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x07, 0x0a,
	0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x13, 0x5a, 0x11, 0x6c, 0x61, 0x69, 0x79, 0x61, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_inner_2home_proto_rawDescOnce sync.Once
	file_inner_2home_proto_rawDescData = file_inner_2home_proto_rawDesc
)

func file_inner_2home_proto_rawDescGZIP() []byte {
	file_inner_2home_proto_rawDescOnce.Do(func() {
		file_inner_2home_proto_rawDescData = protoimpl.X.CompressGZIP(file_inner_2home_proto_rawDescData)
	})
	return file_inner_2home_proto_rawDescData
}

var file_inner_2home_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_inner_2home_proto_goTypes = []interface{}{
	(*C2HoSessionOnline)(nil),            // 0: inner.C2HoSessionOnline
	(*C2HoSessionOffline)(nil),           // 1: inner.C2HoSessionOffline
	(*C2HoSessionHeartbeat)(nil),         // 2: inner.C2HoSessionHeartbeat
	(*Web2HoDeletePlayer)(nil),           // 3: inner.Web2HoDeletePlayer
	(*Gr2HoGroupDisband)(nil),            // 4: inner.Gr2HoGroupDisband
	(*GroupActiveEvent)(nil),             // 5: inner.GroupActiveEvent
	(*SendPrivateChatMsg)(nil),           // 6: inner.SendPrivateChatMsg
	(*C2HoSessionOnline_Request)(nil),    // 7: inner.C2HoSessionOnline.Request
	(*C2HoSessionOnline_Reply)(nil),      // 8: inner.C2HoSessionOnline.Reply
	(*C2HoSessionOffline_Request)(nil),   // 9: inner.C2HoSessionOffline.Request
	(*C2HoSessionOffline_Reply)(nil),     // 10: inner.C2HoSessionOffline.Reply
	(*C2HoSessionHeartbeat_Request)(nil), // 11: inner.C2HoSessionHeartbeat.Request
	(*C2HoSessionHeartbeat_Reply)(nil),   // 12: inner.C2HoSessionHeartbeat.Reply
	(*Web2HoDeletePlayer_Request)(nil),   // 13: inner.Web2HoDeletePlayer.Request
	(*Web2HoDeletePlayer_Reply)(nil),     // 14: inner.Web2HoDeletePlayer.Reply
	(*Gr2HoGroupDisband_Request)(nil),    // 15: inner.Gr2HoGroupDisband.Request
	(*Gr2HoGroupDisband_Reply)(nil),      // 16: inner.Gr2HoGroupDisband.Reply
	(*GroupActiveEvent_Notify)(nil),      // 17: inner.GroupActiveEvent.Notify
	(*SendPrivateChatMsg_Request)(nil),   // 18: inner.SendPrivateChatMsg.Request
	(*SendPrivateChatMsg_Reply)(nil),     // 19: inner.SendPrivateChatMsg.Reply
	(*actor.PID)(nil),                    // 20: actor.PID
	(common.LoginPlatformType)(0),        // 21: common.LoginPlatformType
	(outer.ChatMsg_MsgType)(0),           // 22: outer.ChatMsg.MsgType
}
var file_inner_2home_proto_depIdxs = []int32{
	20, // 0: inner.C2HoSessionOnline.Request.session:type_name -> actor.PID
	21, // 1: inner.C2HoSessionOnline.Request.loginPlatformType:type_name -> common.LoginPlatformType
	20, // 2: inner.C2HoSessionOffline.Request.session:type_name -> actor.PID
	21, // 3: inner.C2HoSessionOffline.Request.loginPlatformType:type_name -> common.LoginPlatformType
	20, // 4: inner.C2HoSessionHeartbeat.Request.session:type_name -> actor.PID
	21, // 5: inner.C2HoSessionHeartbeat.Request.loginPlatformType:type_name -> common.LoginPlatformType
	22, // 6: inner.SendPrivateChatMsg.Request.msgType:type_name -> outer.ChatMsg.MsgType
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_inner_2home_proto_init() }
func file_inner_2home_proto_init() {
	if File_inner_2home_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inner_2home_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2HoSessionOnline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2HoSessionOffline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2HoSessionHeartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Web2HoDeletePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2HoGroupDisband); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupActiveEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPrivateChatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2HoSessionOnline_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2HoSessionOnline_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2HoSessionOffline_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2HoSessionOffline_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2HoSessionHeartbeat_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2HoSessionHeartbeat_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Web2HoDeletePlayer_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Web2HoDeletePlayer_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2HoGroupDisband_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2HoGroupDisband_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupActiveEvent_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPrivateChatMsg_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2home_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPrivateChatMsg_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inner_2home_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inner_2home_proto_goTypes,
		DependencyIndexes: file_inner_2home_proto_depIdxs,
		MessageInfos:      file_inner_2home_proto_msgTypes,
	}.Build()
	File_inner_2home_proto = out.File
	file_inner_2home_proto_rawDesc = nil
	file_inner_2home_proto_goTypes = nil
	file_inner_2home_proto_depIdxs = nil
}
