// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.5.1
// source: inner/2wechat.proto

package inner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//大厅通知微信群--群状态--找人
type Ha2WechatLookingMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ha2WechatLookingMsg) Reset() {
	*x = Ha2WechatLookingMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2wechat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ha2WechatLookingMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ha2WechatLookingMsg) ProtoMessage() {}

func (x *Ha2WechatLookingMsg) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2wechat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ha2WechatLookingMsg.ProtoReflect.Descriptor instead.
func (*Ha2WechatLookingMsg) Descriptor() ([]byte, []int) {
	return file_inner_2wechat_proto_rawDescGZIP(), []int{0}
}

//群机器人通知微信群--
type Ro2WechatLookingMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ro2WechatLookingMsg) Reset() {
	*x = Ro2WechatLookingMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2wechat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ro2WechatLookingMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ro2WechatLookingMsg) ProtoMessage() {}

func (x *Ro2WechatLookingMsg) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2wechat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ro2WechatLookingMsg.ProtoReflect.Descriptor instead.
func (*Ro2WechatLookingMsg) Descriptor() ([]byte, []int) {
	return file_inner_2wechat_proto_rawDescGZIP(), []int{1}
}

type Ha2WechatLookingMsg_Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid           uint64 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	GroupName     string `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	VoiceRoomName string `protobuf:"bytes,3,opt,name=voiceRoomName,proto3" json:"voiceRoomName,omitempty"`
	PlayerCount   uint32 `protobuf:"varint,4,opt,name=playerCount,proto3" json:"playerCount,omitempty"`
}

func (x *Ha2WechatLookingMsg_Group) Reset() {
	*x = Ha2WechatLookingMsg_Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2wechat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ha2WechatLookingMsg_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ha2WechatLookingMsg_Group) ProtoMessage() {}

func (x *Ha2WechatLookingMsg_Group) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2wechat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ha2WechatLookingMsg_Group.ProtoReflect.Descriptor instead.
func (*Ha2WechatLookingMsg_Group) Descriptor() ([]byte, []int) {
	return file_inner_2wechat_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Ha2WechatLookingMsg_Group) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Ha2WechatLookingMsg_Group) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Ha2WechatLookingMsg_Group) GetVoiceRoomName() string {
	if x != nil {
		return x.VoiceRoomName
	}
	return ""
}

func (x *Ha2WechatLookingMsg_Group) GetPlayerCount() uint32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

type Ha2WechatLookingMsg_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameType string                       `protobuf:"bytes,1,opt,name=gameType,proto3" json:"gameType,omitempty"`
	Groups   []*Ha2WechatLookingMsg_Group `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *Ha2WechatLookingMsg_Notify) Reset() {
	*x = Ha2WechatLookingMsg_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2wechat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ha2WechatLookingMsg_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ha2WechatLookingMsg_Notify) ProtoMessage() {}

func (x *Ha2WechatLookingMsg_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2wechat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ha2WechatLookingMsg_Notify.ProtoReflect.Descriptor instead.
func (*Ha2WechatLookingMsg_Notify) Descriptor() ([]byte, []int) {
	return file_inner_2wechat_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Ha2WechatLookingMsg_Notify) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *Ha2WechatLookingMsg_Notify) GetGroups() []*Ha2WechatLookingMsg_Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type Ro2WechatLookingMsg_Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid            uint64 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	GroupName      string `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	GroupVoiceName string `protobuf:"bytes,3,opt,name=groupVoiceName,proto3" json:"groupVoiceName,omitempty"`
	PlayerCount    uint32 `protobuf:"varint,4,opt,name=playerCount,proto3" json:"playerCount,omitempty"`
}

func (x *Ro2WechatLookingMsg_Group) Reset() {
	*x = Ro2WechatLookingMsg_Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2wechat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ro2WechatLookingMsg_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ro2WechatLookingMsg_Group) ProtoMessage() {}

func (x *Ro2WechatLookingMsg_Group) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2wechat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ro2WechatLookingMsg_Group.ProtoReflect.Descriptor instead.
func (*Ro2WechatLookingMsg_Group) Descriptor() ([]byte, []int) {
	return file_inner_2wechat_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Ro2WechatLookingMsg_Group) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Ro2WechatLookingMsg_Group) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Ro2WechatLookingMsg_Group) GetGroupVoiceName() string {
	if x != nil {
		return x.GroupVoiceName
	}
	return ""
}

func (x *Ro2WechatLookingMsg_Group) GetPlayerCount() uint32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

type Ro2WechatLookingMsg_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameType string                     `protobuf:"bytes,1,opt,name=gameType,proto3" json:"gameType,omitempty"`
	Group    *Ro2WechatLookingMsg_Group `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *Ro2WechatLookingMsg_Notify) Reset() {
	*x = Ro2WechatLookingMsg_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_2wechat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ro2WechatLookingMsg_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ro2WechatLookingMsg_Notify) ProtoMessage() {}

func (x *Ro2WechatLookingMsg_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_inner_2wechat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ro2WechatLookingMsg_Notify.ProtoReflect.Descriptor instead.
func (*Ro2WechatLookingMsg_Notify) Descriptor() ([]byte, []int) {
	return file_inner_2wechat_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Ro2WechatLookingMsg_Notify) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *Ro2WechatLookingMsg_Notify) GetGroup() *Ro2WechatLookingMsg_Group {
	if x != nil {
		return x.Group
	}
	return nil
}

var File_inner_2wechat_proto protoreflect.FileDescriptor

var file_inner_2wechat_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x32, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0xf6, 0x01, 0x0a,
	0x13, 0x48, 0x61, 0x32, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x4d, 0x73, 0x67, 0x1a, 0x7f, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x5e, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x32, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x06, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0xf7, 0x01, 0x0a, 0x13, 0x52, 0x6f, 0x32, 0x57, 0x65, 0x63,
	0x68, 0x61, 0x74, 0x4c, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67, 0x1a, 0x81, 0x01,
	0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x56, 0x6f, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x1a, 0x5c, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x67,
	0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67,
	0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x52,
	0x6f, 0x32, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x4d,
	0x73, 0x67, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x42,
	0x13, 0x5a, 0x11, 0x6c, 0x61, 0x69, 0x79, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inner_2wechat_proto_rawDescOnce sync.Once
	file_inner_2wechat_proto_rawDescData = file_inner_2wechat_proto_rawDesc
)

func file_inner_2wechat_proto_rawDescGZIP() []byte {
	file_inner_2wechat_proto_rawDescOnce.Do(func() {
		file_inner_2wechat_proto_rawDescData = protoimpl.X.CompressGZIP(file_inner_2wechat_proto_rawDescData)
	})
	return file_inner_2wechat_proto_rawDescData
}

var file_inner_2wechat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_inner_2wechat_proto_goTypes = []interface{}{
	(*Ha2WechatLookingMsg)(nil),        // 0: inner.Ha2WechatLookingMsg
	(*Ro2WechatLookingMsg)(nil),        // 1: inner.Ro2WechatLookingMsg
	(*Ha2WechatLookingMsg_Group)(nil),  // 2: inner.Ha2WechatLookingMsg.Group
	(*Ha2WechatLookingMsg_Notify)(nil), // 3: inner.Ha2WechatLookingMsg.Notify
	(*Ro2WechatLookingMsg_Group)(nil),  // 4: inner.Ro2WechatLookingMsg.Group
	(*Ro2WechatLookingMsg_Notify)(nil), // 5: inner.Ro2WechatLookingMsg.Notify
}
var file_inner_2wechat_proto_depIdxs = []int32{
	2, // 0: inner.Ha2WechatLookingMsg.Notify.groups:type_name -> inner.Ha2WechatLookingMsg.Group
	4, // 1: inner.Ro2WechatLookingMsg.Notify.group:type_name -> inner.Ro2WechatLookingMsg.Group
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_inner_2wechat_proto_init() }
func file_inner_2wechat_proto_init() {
	if File_inner_2wechat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inner_2wechat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ha2WechatLookingMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2wechat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ro2WechatLookingMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2wechat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ha2WechatLookingMsg_Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2wechat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ha2WechatLookingMsg_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2wechat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ro2WechatLookingMsg_Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_2wechat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ro2WechatLookingMsg_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inner_2wechat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inner_2wechat_proto_goTypes,
		DependencyIndexes: file_inner_2wechat_proto_depIdxs,
		MessageInfos:      file_inner_2wechat_proto_msgTypes,
	}.Build()
	File_inner_2wechat_proto = out.File
	file_inner_2wechat_proto_rawDesc = nil
	file_inner_2wechat_proto_goTypes = nil
	file_inner_2wechat_proto_depIdxs = nil
}
