// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.5.1
// source: inner/awake.proto

package inner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//唤醒大厅
type AwakeHall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AwakeHall) Reset() {
	*x = AwakeHall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_awake_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AwakeHall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwakeHall) ProtoMessage() {}

func (x *AwakeHall) ProtoReflect() protoreflect.Message {
	mi := &file_inner_awake_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwakeHall.ProtoReflect.Descriptor instead.
func (*AwakeHall) Descriptor() ([]byte, []int) {
	return file_inner_awake_proto_rawDescGZIP(), []int{0}
}

//唤醒微信
type AwakeWechat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AwakeWechat) Reset() {
	*x = AwakeWechat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_awake_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AwakeWechat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwakeWechat) ProtoMessage() {}

func (x *AwakeWechat) ProtoReflect() protoreflect.Message {
	mi := &file_inner_awake_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwakeWechat.ProtoReflect.Descriptor instead.
func (*AwakeWechat) Descriptor() ([]byte, []int) {
	return file_inner_awake_proto_rawDescGZIP(), []int{1}
}

type AwakeHall_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AwakeHall_Request) Reset() {
	*x = AwakeHall_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_awake_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AwakeHall_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwakeHall_Request) ProtoMessage() {}

func (x *AwakeHall_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_awake_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwakeHall_Request.ProtoReflect.Descriptor instead.
func (*AwakeHall_Request) Descriptor() ([]byte, []int) {
	return file_inner_awake_proto_rawDescGZIP(), []int{0, 0}
}

type AwakeHall_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AwakeHall_Reply) Reset() {
	*x = AwakeHall_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_awake_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AwakeHall_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwakeHall_Reply) ProtoMessage() {}

func (x *AwakeHall_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_awake_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwakeHall_Reply.ProtoReflect.Descriptor instead.
func (*AwakeHall_Reply) Descriptor() ([]byte, []int) {
	return file_inner_awake_proto_rawDescGZIP(), []int{0, 1}
}

type AwakeWechat_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AwakeWechat_Request) Reset() {
	*x = AwakeWechat_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_awake_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AwakeWechat_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwakeWechat_Request) ProtoMessage() {}

func (x *AwakeWechat_Request) ProtoReflect() protoreflect.Message {
	mi := &file_inner_awake_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwakeWechat_Request.ProtoReflect.Descriptor instead.
func (*AwakeWechat_Request) Descriptor() ([]byte, []int) {
	return file_inner_awake_proto_rawDescGZIP(), []int{1, 0}
}

type AwakeWechat_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AwakeWechat_Reply) Reset() {
	*x = AwakeWechat_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_awake_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AwakeWechat_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwakeWechat_Reply) ProtoMessage() {}

func (x *AwakeWechat_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_inner_awake_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwakeWechat_Reply.ProtoReflect.Descriptor instead.
func (*AwakeWechat_Reply) Descriptor() ([]byte, []int) {
	return file_inner_awake_proto_rawDescGZIP(), []int{1, 1}
}

var File_inner_awake_proto protoreflect.FileDescriptor

var file_inner_awake_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x61, 0x77, 0x61, 0x6b, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x1f, 0x0a, 0x09, 0x41, 0x77,
	0x61, 0x6b, 0x65, 0x48, 0x61, 0x6c, 0x6c, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x21, 0x0a, 0x0b, 0x41,
	0x77, 0x61, 0x6b, 0x65, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x13,
	0x5a, 0x11, 0x6c, 0x61, 0x69, 0x79, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inner_awake_proto_rawDescOnce sync.Once
	file_inner_awake_proto_rawDescData = file_inner_awake_proto_rawDesc
)

func file_inner_awake_proto_rawDescGZIP() []byte {
	file_inner_awake_proto_rawDescOnce.Do(func() {
		file_inner_awake_proto_rawDescData = protoimpl.X.CompressGZIP(file_inner_awake_proto_rawDescData)
	})
	return file_inner_awake_proto_rawDescData
}

var file_inner_awake_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_inner_awake_proto_goTypes = []interface{}{
	(*AwakeHall)(nil),           // 0: inner.AwakeHall
	(*AwakeWechat)(nil),         // 1: inner.AwakeWechat
	(*AwakeHall_Request)(nil),   // 2: inner.AwakeHall.Request
	(*AwakeHall_Reply)(nil),     // 3: inner.AwakeHall.Reply
	(*AwakeWechat_Request)(nil), // 4: inner.AwakeWechat.Request
	(*AwakeWechat_Reply)(nil),   // 5: inner.AwakeWechat.Reply
}
var file_inner_awake_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inner_awake_proto_init() }
func file_inner_awake_proto_init() {
	if File_inner_awake_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inner_awake_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AwakeHall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_awake_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AwakeWechat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_awake_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AwakeHall_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_awake_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AwakeHall_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_awake_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AwakeWechat_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_awake_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AwakeWechat_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inner_awake_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inner_awake_proto_goTypes,
		DependencyIndexes: file_inner_awake_proto_depIdxs,
		MessageInfos:      file_inner_awake_proto_msgTypes,
	}.Build()
	File_inner_awake_proto = out.File
	file_inner_awake_proto_rawDesc = nil
	file_inner_awake_proto_goTypes = nil
	file_inner_awake_proto_depIdxs = nil
}
