// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.5.1
// source: inner/robot.proto

package inner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//首次添加机器人
type Gr2RoAddRobot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Gr2RoAddRobot) Reset() {
	*x = Gr2RoAddRobot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2RoAddRobot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2RoAddRobot) ProtoMessage() {}

func (x *Gr2RoAddRobot) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2RoAddRobot.ProtoReflect.Descriptor instead.
func (*Gr2RoAddRobot) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{0}
}

//@机器人的聊天消息
type Gr2RoAtRobotChatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Gr2RoAtRobotChatMsg) Reset() {
	*x = Gr2RoAtRobotChatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2RoAtRobotChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2RoAtRobotChatMsg) ProtoMessage() {}

func (x *Gr2RoAtRobotChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2RoAtRobotChatMsg.ProtoReflect.Descriptor instead.
func (*Gr2RoAtRobotChatMsg) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{1}
}

//机器人说的聊天消息
type Ro2GrRobotSayChatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ro2GrRobotSayChatMsg) Reset() {
	*x = Ro2GrRobotSayChatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ro2GrRobotSayChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ro2GrRobotSayChatMsg) ProtoMessage() {}

func (x *Ro2GrRobotSayChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ro2GrRobotSayChatMsg.ProtoReflect.Descriptor instead.
func (*Ro2GrRobotSayChatMsg) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{2}
}

//摇人--老版
type Gr2RoLookingPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Gr2RoLookingPlayer) Reset() {
	*x = Gr2RoLookingPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2RoLookingPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2RoLookingPlayer) ProtoMessage() {}

func (x *Gr2RoLookingPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2RoLookingPlayer.ProtoReflect.Descriptor instead.
func (*Gr2RoLookingPlayer) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{3}
}

//在麦上的玩家的人数变化
type Gr2RoOnMicPlayerCountChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Gr2RoOnMicPlayerCountChanged) Reset() {
	*x = Gr2RoOnMicPlayerCountChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2RoOnMicPlayerCountChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2RoOnMicPlayerCountChanged) ProtoMessage() {}

func (x *Gr2RoOnMicPlayerCountChanged) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2RoOnMicPlayerCountChanged.ProtoReflect.Descriptor instead.
func (*Gr2RoOnMicPlayerCountChanged) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{4}
}

//摇人--新版
type Gr2RoNeedInviteBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Gr2RoNeedInviteBroadcast) Reset() {
	*x = Gr2RoNeedInviteBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2RoNeedInviteBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2RoNeedInviteBroadcast) ProtoMessage() {}

func (x *Gr2RoNeedInviteBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2RoNeedInviteBroadcast.ProtoReflect.Descriptor instead.
func (*Gr2RoNeedInviteBroadcast) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{5}
}

//通知微信群--找人
type Ro2WechatLookingPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ro2WechatLookingPlayer) Reset() {
	*x = Ro2WechatLookingPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ro2WechatLookingPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ro2WechatLookingPlayer) ProtoMessage() {}

func (x *Ro2WechatLookingPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ro2WechatLookingPlayer.ProtoReflect.Descriptor instead.
func (*Ro2WechatLookingPlayer) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{6}
}

//通知微信群--定时广播需要玩家的group
type Ro2WechatGroupState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ro2WechatGroupState) Reset() {
	*x = Ro2WechatGroupState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ro2WechatGroupState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ro2WechatGroupState) ProtoMessage() {}

func (x *Ro2WechatGroupState) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ro2WechatGroupState.ProtoReflect.Descriptor instead.
func (*Ro2WechatGroupState) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{7}
}

type Gr2RoAddRobot_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Gr2RoAddRobot_Notify) Reset() {
	*x = Gr2RoAddRobot_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2RoAddRobot_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2RoAddRobot_Notify) ProtoMessage() {}

func (x *Gr2RoAddRobot_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2RoAddRobot_Notify.ProtoReflect.Descriptor instead.
func (*Gr2RoAddRobot_Notify) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{0, 0}
}

type Gr2RoAtRobotChatMsg_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendUid uint64 `protobuf:"varint,1,opt,name=sendUid,proto3" json:"sendUid,omitempty"` //发送着id
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`  //消息内容
}

func (x *Gr2RoAtRobotChatMsg_Notify) Reset() {
	*x = Gr2RoAtRobotChatMsg_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2RoAtRobotChatMsg_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2RoAtRobotChatMsg_Notify) ProtoMessage() {}

func (x *Gr2RoAtRobotChatMsg_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2RoAtRobotChatMsg_Notify.ProtoReflect.Descriptor instead.
func (*Gr2RoAtRobotChatMsg_Notify) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Gr2RoAtRobotChatMsg_Notify) GetSendUid() uint64 {
	if x != nil {
		return x.SendUid
	}
	return 0
}

func (x *Gr2RoAtRobotChatMsg_Notify) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Ro2GrRobotSayChatMsg_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId    uint64 `protobuf:"varint,1,opt,name=robotId,proto3" json:"robotId,omitempty"`       //机器人自身
	ReplyToUid uint64 `protobuf:"varint,2,opt,name=replyToUid,proto3" json:"replyToUid,omitempty"` //回复发送者 0表示无回复对象
	Content    string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`        //消息内容
}

func (x *Ro2GrRobotSayChatMsg_Notify) Reset() {
	*x = Ro2GrRobotSayChatMsg_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ro2GrRobotSayChatMsg_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ro2GrRobotSayChatMsg_Notify) ProtoMessage() {}

func (x *Ro2GrRobotSayChatMsg_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ro2GrRobotSayChatMsg_Notify.ProtoReflect.Descriptor instead.
func (*Ro2GrRobotSayChatMsg_Notify) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Ro2GrRobotSayChatMsg_Notify) GetRobotId() uint64 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *Ro2GrRobotSayChatMsg_Notify) GetReplyToUid() uint64 {
	if x != nil {
		return x.ReplyToUid
	}
	return 0
}

func (x *Ro2GrRobotSayChatMsg_Notify) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Gr2RoLookingPlayer_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid            uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                      //谁触发的
	GroupName      string `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`           //群名
	GroupVoiceName string `protobuf:"bytes,3,opt,name=groupVoiceName,proto3" json:"groupVoiceName,omitempty"` //群语音名字
	GameType       string `protobuf:"bytes,4,opt,name=gameType,proto3" json:"gameType,omitempty"`             //游戏类型
}

func (x *Gr2RoLookingPlayer_Notify) Reset() {
	*x = Gr2RoLookingPlayer_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2RoLookingPlayer_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2RoLookingPlayer_Notify) ProtoMessage() {}

func (x *Gr2RoLookingPlayer_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2RoLookingPlayer_Notify.ProtoReflect.Descriptor instead.
func (*Gr2RoLookingPlayer_Notify) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Gr2RoLookingPlayer_Notify) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Gr2RoLookingPlayer_Notify) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Gr2RoLookingPlayer_Notify) GetGroupVoiceName() string {
	if x != nil {
		return x.GroupVoiceName
	}
	return ""
}

func (x *Gr2RoLookingPlayer_Notify) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

type Gr2RoOnMicPlayerCountChanged_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OnMicPlayerCount uint32 `protobuf:"varint,1,opt,name=onMicPlayerCount,proto3" json:"onMicPlayerCount,omitempty"`
}

func (x *Gr2RoOnMicPlayerCountChanged_Notify) Reset() {
	*x = Gr2RoOnMicPlayerCountChanged_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2RoOnMicPlayerCountChanged_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2RoOnMicPlayerCountChanged_Notify) ProtoMessage() {}

func (x *Gr2RoOnMicPlayerCountChanged_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2RoOnMicPlayerCountChanged_Notify.ProtoReflect.Descriptor instead.
func (*Gr2RoOnMicPlayerCountChanged_Notify) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Gr2RoOnMicPlayerCountChanged_Notify) GetOnMicPlayerCount() uint32 {
	if x != nil {
		return x.OnMicPlayerCount
	}
	return 0
}

type Gr2RoNeedInviteBroadcast_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid            uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                      //谁触发的
	GroupName      string `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`           //群名
	GroupVoiceName string `protobuf:"bytes,3,opt,name=groupVoiceName,proto3" json:"groupVoiceName,omitempty"` //群语音名字
	GameType       string `protobuf:"bytes,4,opt,name=gameType,proto3" json:"gameType,omitempty"`             //游戏类型
}

func (x *Gr2RoNeedInviteBroadcast_Notify) Reset() {
	*x = Gr2RoNeedInviteBroadcast_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gr2RoNeedInviteBroadcast_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gr2RoNeedInviteBroadcast_Notify) ProtoMessage() {}

func (x *Gr2RoNeedInviteBroadcast_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gr2RoNeedInviteBroadcast_Notify.ProtoReflect.Descriptor instead.
func (*Gr2RoNeedInviteBroadcast_Notify) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Gr2RoNeedInviteBroadcast_Notify) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Gr2RoNeedInviteBroadcast_Notify) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Gr2RoNeedInviteBroadcast_Notify) GetGroupVoiceName() string {
	if x != nil {
		return x.GroupVoiceName
	}
	return ""
}

func (x *Gr2RoNeedInviteBroadcast_Notify) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

type Ro2WechatLookingPlayer_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid        uint64 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`               //通过uid来生成分享链接
	OnMicCount int32  `protobuf:"varint,2,opt,name=onMicCount,proto3" json:"onMicCount,omitempty"` //在麦人数
}

func (x *Ro2WechatLookingPlayer_Notify) Reset() {
	*x = Ro2WechatLookingPlayer_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ro2WechatLookingPlayer_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ro2WechatLookingPlayer_Notify) ProtoMessage() {}

func (x *Ro2WechatLookingPlayer_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ro2WechatLookingPlayer_Notify.ProtoReflect.Descriptor instead.
func (*Ro2WechatLookingPlayer_Notify) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Ro2WechatLookingPlayer_Notify) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Ro2WechatLookingPlayer_Notify) GetOnMicCount() int32 {
	if x != nil {
		return x.OnMicCount
	}
	return 0
}

type Ro2WechatGroupState_GroupState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid        uint64 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`               //通过uid来生成分享链接
	OnMicCount int32  `protobuf:"varint,2,opt,name=onMicCount,proto3" json:"onMicCount,omitempty"` //在麦人数
}

func (x *Ro2WechatGroupState_GroupState) Reset() {
	*x = Ro2WechatGroupState_GroupState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ro2WechatGroupState_GroupState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ro2WechatGroupState_GroupState) ProtoMessage() {}

func (x *Ro2WechatGroupState_GroupState) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ro2WechatGroupState_GroupState.ProtoReflect.Descriptor instead.
func (*Ro2WechatGroupState_GroupState) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Ro2WechatGroupState_GroupState) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Ro2WechatGroupState_GroupState) GetOnMicCount() int32 {
	if x != nil {
		return x.OnMicCount
	}
	return 0
}

type Ro2WechatGroupState_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []*Ro2WechatGroupState_GroupState `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *Ro2WechatGroupState_Notify) Reset() {
	*x = Ro2WechatGroupState_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_robot_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ro2WechatGroupState_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ro2WechatGroupState_Notify) ProtoMessage() {}

func (x *Ro2WechatGroupState_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_inner_robot_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ro2WechatGroupState_Notify.ProtoReflect.Descriptor instead.
func (*Ro2WechatGroupState_Notify) Descriptor() ([]byte, []int) {
	return file_inner_robot_proto_rawDescGZIP(), []int{7, 1}
}

func (x *Ro2WechatGroupState_Notify) GetGroups() []*Ro2WechatGroupState_GroupState {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_inner_robot_proto protoreflect.FileDescriptor

var file_inner_robot_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x19, 0x0a, 0x0d, 0x47, 0x72,
	0x32, 0x52, 0x6f, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x1a, 0x08, 0x0a, 0x06, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x22, 0x53, 0x0a, 0x13, 0x47, 0x72, 0x32, 0x52, 0x6f, 0x41, 0x74,
	0x52, 0x6f, 0x62, 0x6f, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x1a, 0x3c, 0x0a, 0x06,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x6e, 0x64, 0x55, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x65, 0x6e, 0x64, 0x55, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x74, 0x0a, 0x14, 0x52, 0x6f,
	0x32, 0x47, 0x72, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x53, 0x61, 0x79, 0x43, 0x68, 0x61, 0x74, 0x4d,
	0x73, 0x67, 0x1a, 0x5c, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72,
	0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x54,
	0x6f, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6c,
	0x79, 0x54, 0x6f, 0x55, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0x92, 0x01, 0x0a, 0x12, 0x47, 0x72, 0x32, 0x52, 0x6f, 0x4c, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x1a, 0x7c, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x56, 0x6f, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x54, 0x0a, 0x1c, 0x47, 0x72, 0x32, 0x52, 0x6f, 0x4f, 0x6e,
	0x4d, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x64, 0x1a, 0x34, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12,
	0x2a, 0x0a, 0x10, 0x6f, 0x6e, 0x4d, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x6f, 0x6e, 0x4d, 0x69, 0x63,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x98, 0x01, 0x0a, 0x18,
	0x47, 0x72, 0x32, 0x52, 0x6f, 0x4e, 0x65, 0x65, 0x64, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x1a, 0x7c, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x6f, 0x69, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x54, 0x0a, 0x16, 0x52, 0x6f, 0x32, 0x57, 0x65, 0x63,
	0x68, 0x61, 0x74, 0x4c, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x1a, 0x3a, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x6f, 0x6e, 0x4d, 0x69, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x6f, 0x6e, 0x4d, 0x69, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x9e, 0x01, 0x0a,
	0x13, 0x52, 0x6f, 0x32, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x1a, 0x3e, 0x0a, 0x0a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x67, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x6e, 0x4d, 0x69, 0x63, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6f, 0x6e, 0x4d, 0x69, 0x63, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x47, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x3d,
	0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25,
	0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x32, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x42, 0x13, 0x5a,
	0x11, 0x6c, 0x61, 0x69, 0x79, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x6e,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inner_robot_proto_rawDescOnce sync.Once
	file_inner_robot_proto_rawDescData = file_inner_robot_proto_rawDesc
)

func file_inner_robot_proto_rawDescGZIP() []byte {
	file_inner_robot_proto_rawDescOnce.Do(func() {
		file_inner_robot_proto_rawDescData = protoimpl.X.CompressGZIP(file_inner_robot_proto_rawDescData)
	})
	return file_inner_robot_proto_rawDescData
}

var file_inner_robot_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_inner_robot_proto_goTypes = []interface{}{
	(*Gr2RoAddRobot)(nil),                       // 0: inner.Gr2RoAddRobot
	(*Gr2RoAtRobotChatMsg)(nil),                 // 1: inner.Gr2RoAtRobotChatMsg
	(*Ro2GrRobotSayChatMsg)(nil),                // 2: inner.Ro2GrRobotSayChatMsg
	(*Gr2RoLookingPlayer)(nil),                  // 3: inner.Gr2RoLookingPlayer
	(*Gr2RoOnMicPlayerCountChanged)(nil),        // 4: inner.Gr2RoOnMicPlayerCountChanged
	(*Gr2RoNeedInviteBroadcast)(nil),            // 5: inner.Gr2RoNeedInviteBroadcast
	(*Ro2WechatLookingPlayer)(nil),              // 6: inner.Ro2WechatLookingPlayer
	(*Ro2WechatGroupState)(nil),                 // 7: inner.Ro2WechatGroupState
	(*Gr2RoAddRobot_Notify)(nil),                // 8: inner.Gr2RoAddRobot.Notify
	(*Gr2RoAtRobotChatMsg_Notify)(nil),          // 9: inner.Gr2RoAtRobotChatMsg.Notify
	(*Ro2GrRobotSayChatMsg_Notify)(nil),         // 10: inner.Ro2GrRobotSayChatMsg.Notify
	(*Gr2RoLookingPlayer_Notify)(nil),           // 11: inner.Gr2RoLookingPlayer.Notify
	(*Gr2RoOnMicPlayerCountChanged_Notify)(nil), // 12: inner.Gr2RoOnMicPlayerCountChanged.Notify
	(*Gr2RoNeedInviteBroadcast_Notify)(nil),     // 13: inner.Gr2RoNeedInviteBroadcast.Notify
	(*Ro2WechatLookingPlayer_Notify)(nil),       // 14: inner.Ro2WechatLookingPlayer.Notify
	(*Ro2WechatGroupState_GroupState)(nil),      // 15: inner.Ro2WechatGroupState.GroupState
	(*Ro2WechatGroupState_Notify)(nil),          // 16: inner.Ro2WechatGroupState.Notify
}
var file_inner_robot_proto_depIdxs = []int32{
	15, // 0: inner.Ro2WechatGroupState.Notify.groups:type_name -> inner.Ro2WechatGroupState.GroupState
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_inner_robot_proto_init() }
func file_inner_robot_proto_init() {
	if File_inner_robot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inner_robot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2RoAddRobot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2RoAtRobotChatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ro2GrRobotSayChatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2RoLookingPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2RoOnMicPlayerCountChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2RoNeedInviteBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ro2WechatLookingPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ro2WechatGroupState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2RoAddRobot_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2RoAtRobotChatMsg_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ro2GrRobotSayChatMsg_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2RoLookingPlayer_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2RoOnMicPlayerCountChanged_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gr2RoNeedInviteBroadcast_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ro2WechatLookingPlayer_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ro2WechatGroupState_GroupState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_robot_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ro2WechatGroupState_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inner_robot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inner_robot_proto_goTypes,
		DependencyIndexes: file_inner_robot_proto_depIdxs,
		MessageInfos:      file_inner_robot_proto_msgTypes,
	}.Build()
	File_inner_robot_proto = out.File
	file_inner_robot_proto_rawDesc = nil
	file_inner_robot_proto_goTypes = nil
	file_inner_robot_proto_depIdxs = nil
}
