// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.5.1
// source: common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginPlatformType int32

const (
	LoginPlatformType_unknownPlatform LoginPlatformType = 0 //未知的平台
	LoginPlatformType_windows         LoginPlatformType = 1
	LoginPlatformType_ios             LoginPlatformType = 2
	LoginPlatformType_android         LoginPlatformType = 3
	LoginPlatformType_web             LoginPlatformType = 4
	LoginPlatformType_macos           LoginPlatformType = 5
	LoginPlatformType_linux           LoginPlatformType = 6
)

// Enum value maps for LoginPlatformType.
var (
	LoginPlatformType_name = map[int32]string{
		0: "unknownPlatform",
		1: "windows",
		2: "ios",
		3: "android",
		4: "web",
		5: "macos",
		6: "linux",
	}
	LoginPlatformType_value = map[string]int32{
		"unknownPlatform": 0,
		"windows":         1,
		"ios":             2,
		"android":         3,
		"web":             4,
		"macos":           5,
		"linux":           6,
	}
)

func (x LoginPlatformType) Enum() *LoginPlatformType {
	p := new(LoginPlatformType)
	*p = x
	return p
}

func (x LoginPlatformType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginPlatformType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[0].Descriptor()
}

func (LoginPlatformType) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[0]
}

func (x LoginPlatformType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginPlatformType.Descriptor instead.
func (LoginPlatformType) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

type UserDef_UserType int32

const (
	UserDef_Unknown UserDef_UserType = 0 //未知类型
	UserDef_User    UserDef_UserType = 1 //用户
	UserDef_Robot   UserDef_UserType = 2 //机器人
)

// Enum value maps for UserDef_UserType.
var (
	UserDef_UserType_name = map[int32]string{
		0: "Unknown",
		1: "User",
		2: "Robot",
	}
	UserDef_UserType_value = map[string]int32{
		"Unknown": 0,
		"User":    1,
		"Robot":   2,
	}
)

func (x UserDef_UserType) Enum() *UserDef_UserType {
	p := new(UserDef_UserType)
	*p = x
	return p
}

func (x UserDef_UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserDef_UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[1].Descriptor()
}

func (UserDef_UserType) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[1]
}

func (x UserDef_UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserDef_UserType.Descriptor instead.
func (UserDef_UserType) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0, 0}
}

//用户类型
type GroupPermissionsDef_Type int32

const (
	GroupPermissionsDef_UnknownType GroupPermissionsDef_Type = 0 //未知类型
	GroupPermissionsDef_User        GroupPermissionsDef_Type = 1 //普通用户
	GroupPermissionsDef_Admin       GroupPermissionsDef_Type = 2 //管理员 MuteOtherVoice
)

// Enum value maps for GroupPermissionsDef_Type.
var (
	GroupPermissionsDef_Type_name = map[int32]string{
		0: "UnknownType",
		1: "User",
		2: "Admin",
	}
	GroupPermissionsDef_Type_value = map[string]int32{
		"UnknownType": 0,
		"User":        1,
		"Admin":       2,
	}
)

func (x GroupPermissionsDef_Type) Enum() *GroupPermissionsDef_Type {
	p := new(GroupPermissionsDef_Type)
	*p = x
	return p
}

func (x GroupPermissionsDef_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupPermissionsDef_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[2].Descriptor()
}

func (GroupPermissionsDef_Type) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[2]
}

func (x GroupPermissionsDef_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupPermissionsDef_Type.Descriptor instead.
func (GroupPermissionsDef_Type) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1, 0}
}

//需要权限的功能
type GroupPermissionsDef_Access int32

const (
	GroupPermissionsDef_UnknownAccess     GroupPermissionsDef_Access = 0 //未知类型
	GroupPermissionsDef_ChangePermissions GroupPermissionsDef_Access = 1 //设置管理员权限
	GroupPermissionsDef_MuteOther         GroupPermissionsDef_Access = 2 //静音其他用户
)

// Enum value maps for GroupPermissionsDef_Access.
var (
	GroupPermissionsDef_Access_name = map[int32]string{
		0: "UnknownAccess",
		1: "ChangePermissions",
		2: "MuteOther",
	}
	GroupPermissionsDef_Access_value = map[string]int32{
		"UnknownAccess":     0,
		"ChangePermissions": 1,
		"MuteOther":         2,
	}
)

func (x GroupPermissionsDef_Access) Enum() *GroupPermissionsDef_Access {
	p := new(GroupPermissionsDef_Access)
	*p = x
	return p
}

func (x GroupPermissionsDef_Access) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupPermissionsDef_Access) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[3].Descriptor()
}

func (GroupPermissionsDef_Access) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[3]
}

func (x GroupPermissionsDef_Access) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupPermissionsDef_Access.Descriptor instead.
func (GroupPermissionsDef_Access) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1, 1}
}

type UserDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserDef) Reset() {
	*x = UserDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDef) ProtoMessage() {}

func (x *UserDef) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDef.ProtoReflect.Descriptor instead.
func (*UserDef) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

//群权限相关
type GroupPermissionsDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupPermissionsDef) Reset() {
	*x = GroupPermissionsDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupPermissionsDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPermissionsDef) ProtoMessage() {}

func (x *GroupPermissionsDef) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPermissionsDef.ProtoReflect.Descriptor instead.
func (*GroupPermissionsDef) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

var File_common_common_proto protoreflect.FileDescriptor

var file_common_common_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x37, 0x0a,
	0x07, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x22, 0x2c, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x10, 0x02, 0x22, 0x86, 0x01, 0x0a, 0x13, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x44, 0x65, 0x66, 0x22, 0x2c,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x10, 0x02, 0x22, 0x41, 0x0a, 0x06,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x10, 0x01,
	0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x75, 0x74, 0x65, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x10, 0x02, 0x2a,
	0x6a, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x50,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x77, 0x69, 0x6e,
	0x64, 0x6f, 0x77, 0x73, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x69, 0x6f, 0x73, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03,
	0x77, 0x65, 0x62, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x10, 0x05,
	0x12, 0x09, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x10, 0x06, 0x42, 0x14, 0x5a, 0x12, 0x6c,
	0x61, 0x69, 0x79, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData = file_common_common_proto_rawDesc
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_common_proto_rawDescData)
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_common_proto_goTypes = []interface{}{
	(LoginPlatformType)(0),          // 0: common.LoginPlatformType
	(UserDef_UserType)(0),           // 1: common.UserDef.UserType
	(GroupPermissionsDef_Type)(0),   // 2: common.GroupPermissionsDef.Type
	(GroupPermissionsDef_Access)(0), // 3: common.GroupPermissionsDef.Access
	(*UserDef)(nil),                 // 4: common.UserDef
	(*GroupPermissionsDef)(nil),     // 5: common.GroupPermissionsDef
}
var file_common_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupPermissionsDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_common_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		EnumInfos:         file_common_common_proto_enumTypes,
		MessageInfos:      file_common_common_proto_msgTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_rawDesc = nil
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
