#是否启用版本号管理配置
EnableCheck = false
#当前可用的客户端版本号(类型:字符串数组)
[LastVersion]
Version = "0.0.8"
Title = """有新版本更新"""
Detail = """1.修复了某些已知bug
2.增加了一些新功能
"""
#版本是否可用,默认不可用[false或者不在列表的版本都为不可用]
[VersionAvailable]
"0.0.0" = false # 版本废弃不可用必须强更
"0.0.1" = false # 版本废弃不可用必须强更
"1.0.0" = true # 版本可用
"0.0.7" = true
"0.0.8" = true