#错误信息返回
Error.UnknownErr = "未知错误"
Error.Error = "通用错误"
Error.InnerError = "内部错误"
Error.InnerRpcError = "rpc错误"
Error.MsgUnmarshalErr = "消息格式错误"
Error.UnsupportedMsgType = "不支持的消息内省"
Error.NotImpl = "未实现的接口"
Error.RpcTimeout = "rpc处理超时"
Error.TokenNotExist = "token未设置"
Error.TokenFormatErr = "token格式错误"
Error.NotFoundMethod = "没找到对应的方法"
Error.NotFoundComponent = "没找到对应的组件"
Error.MsgDefineErr = "消息缺少必要的字段"
Error.EnumNotFoundImpl = "没有对应的类型实现"
Error.UidNotFound = "没有找到uid"
Error.NotFoundTargetId = "没找到目标id"
Error.TokenErr = "token校验失败"
Error.NoAccess = "无权操作"
Error.RobotNotExist = "机器人不存在"
Error.AppVersionNeedUpdate = "app需要更新，请在官网下载最新包"
Error.GmAuthError = "gm授权失败"
Error.ActorInitError = "init初始化错误"
Error.UserNotExist = "用户不存在"
Error.ChatLenLimit = "聊天内容过长"
Error.NowNotInGroup = "当前没在群中，需要先进入群"
Error.MustQuitAllGroupBefore = "必选先解散所有的群"
Error.GameTypeNotExist = "游戏类型不存在"
Error.PlatformTypeNotExist = "平台类型不存在"
Error.UserNameLenIllegal = "用户名称在1-12字之间"
Error.UserDesLenIllegal = "用户描述长度不合法"
Error.GroupNotExist = "群不存在"
Error.GroupCountFull = "最多可以加入50个房间，退出一些再来加入吧"
Error.CreateGroupCountFull = "最多可以创建3个房间，解散一些再来创建吧"
Error.SelfGroup = "这是自己的群"
Error.NotSelfGroup = "这不是自己的群"
Error.NotInGroup = "不在群中"
Error.GroupIdFormatErr = "群Id格式错误"
Error.GroupSubIdFull = "房间数量已满"
Error.GroupPlayerFull = "群人数已经满"
Error.GroupNameLenIllegal = "房间名称在2-20字之间"
Error.GroupDesLenIllegal = "群描述长度不合法"
Error.GroupOnlineFull = "群同时在线人数已满，请稍等"
Error.JoinAccessDenied = "群主没有开启加入权限"
Error.VoiceRoomNameIllegal = "语音房间的名字长度为1-16个字"
Error.GroupActivityNotExist = "群活动不存在"
Error.GroupActivityFull = "群活动已满，请先删除一些过期的活动"
Error.GroupActivityTimeIllegal = "群活动时间非法"
Error.GroupActivityExpired = "群活动已过期"
Error.GroupActivityTitleLenIllegal = "标题长度在1-40个字"
Error.GroupActivityDesLenIllegal = "描述长度需小于200个字"
Error.GroupActivitySignUpRewardLenIllegal = "备注需小于100个字"
Error.CaptchaTooFrequently = "验证码获取过于频繁"
Error.CaptchaExpire = "验证码过期"
Error.CaptchaNotEeq = "验证码不匹配"
Error.PhNotIllegal = "手机号非法"
Error.NotHasCaptcha = "验证码无效，请重新申请验证码"
Error.UrlFormatErr = "url格式错误"
Error.NotFoundUpdateFileNamedIcon = "没有找到名为icon的上传文件"
Error.GeTuiCidIsEmpty = "个推的cid没有设置"
Error.GeTuiOpenPushErr = "个推推送开启失败"
Error.GeTuiClosePushErr = "个推推送关闭失败"
Error.WechatWaitingLogin = "微信机器人还未启动完成"