#机器人命令
[Command]
LookingGroup = ["有车吗","有车么"] #查询车队
UpdateWechatGroups = ["更新群信息"] #更新群的信息,执行此命令后会重新获取群的游戏类型
UpdateWechatFriends = ["更新好友信息"] #更新好友的信息,执行此命令后会重新获取好友列表

#机器人Id对应的游戏类型 --注:由服务器人员维护
[RobotGameTypeTmp]
300002 = "胡闹厨房2/全都好吃" #
300003 = "动物派对" #
